upgrade at version 3.5-beta

diff --git a/.deb/usr/bin/i-Haklab-installer b/.deb/usr/bin/i-Haklab-installer
--- a/.deb/usr/bin/i-Haklab-installer
+++ b/.deb/usr/bin/i-Haklab-installer
@@ -9,9 +9,9 @@ source $iHETC/functions
 echo "Getting access to external storage."
 s2=$(df|grep "fuse"|grep -iv emulated|awk -F " " '{print $6}')
 [[ -n $s2 ]] && [[ -w $s2 ]] && {
-	cp -r ${HOME}/.local/share $s2/data/com.termux/files/share;
-	rm -rf ${HOME}/.local/share;
-	ln -s $s2/data/com.termux/files/share ${HOME}/.local/share;
+	[[ -d $s2/Android/data/com.termux/files/tools ]] && {
+		mv $s2/Android/data/com.termux/files/tools/* ${HOME}/.local/share/;
+	}
 }
 
 echo "Installing required python modules (It could take a while) ..."
@@ -24,11 +24,19 @@ for module in trufflehog wheel speedtest-cli frida shodan;do
 done
 
 echo "Installing local tunnel server ..."
-git clone --quiet https://github.com/localtunnel/localtunnel $TMPDIR/localtunnel-server
-cd $TMPDIR/localtunnel-server
-npm install;npm install -g localtunnel
+git clone --quiet https://github.com/localtunnel/localtunnel $TMPDIR/localtunnel
+cd $TMPDIR/localtunnel
+npm install >/dev/null 2>>$LOGFILE
+npm install -g localtunnel >/dev/null 2>>$LOGFILE
 wget -q --tries=20 ${iHDB}/etc/localtunnel/openurl.js -O $PREFIX/lib/node_modules/localtunnel/node_modules/openurl/openurl.js
-rm -rf $TMPDIR/localtunnel-server
+rm -rf $TMPDIR/localtunnel
+
+echo "Installing brute force wordlists (it could take a while) ..."
+git clone --quiet https://github.com/jeanphorn/wordlist.git ${TMPDIR}/wordlist
+mv ${TMPDIR}/wordlist/* ${HOME}/.local/share/wordlist/
+rm -rf ${TMPDIR}/wordlist
+wget --tries=20 --quiet https://www.scrapmaker.com/data/wordlists/dictionaries/rockyou.txt \
+	-O ${HOME}/.local/share/wordlist/rockyou.txt
 
 echo "Setting i-Haklab style."
 ln -s $PREFIX/bin/fish $HOME/.termux/shell 2>>$LOGFILE
@@ -37,17 +45,15 @@ echo "Installing i-Haklab web service (It could take a long time) ..."
 [[ -d ${HOME}/.local/var/service ]] || mkdir -p ${HOME}/.local/var/service
 wget --tries=20 --quiet $iHDB/.local/etc/i-Haklab/www.zip -O ${HOME}/.local/var/service/www.zip
 [[ -e ${HOME}/.local/var/service/www.zip ]] && {
+	unzip -q ${HOME}/.local/var/service/www.zip -d ${HOME}/.local/var/service
+	rm -rf ${HOME}/.local/var/service/www.zip;
 	[[ -n $s2 ]] && [[ -w $s2 ]] && {
-		www="$s2/data/com.termux/files";
-		ln -s $s2/data/com.termux/files/www ${HOME}/.local/var/service/www
-	} || {
-		www="${HOME}/.local/var/service";
+		www="$s2/Android/data/com.termux/files";
+		mv ${HOME}/.local/var/service/www $www
+		ln -s $www/www ${HOME}/.local/var/service/www
 	}
-	unzip -q ${HOME}/.local/var/service/www.zip -d $www;
-	rm -rf ${HOME}/.local/var/service/www.zip
 } || {
-	echo -en $R"E:$W www.zip unreachable ..$R.Aborting.$W";
-	exit 1;
+	echo -en $R"E:$W www.zip unreachable ..$R.Aborting.$W\n";
 }
 
 # SET ROOT USER IF DEVICE IS ROOTED
@@ -88,7 +94,7 @@ set fish_theme bira
 set -g theme_nerd_fonts yes
 set DISPLAY :0
 set PULSE_SERVER 127.0.0.1
-set PATH ${HOME}/.local/bin:${PREFIX}/bin
+set PATH ${PREFIX}/bin:${HOME}/.local/bin
 set HOME /data/data/com.termux/files/home
 set GOPATH /data/data/com.termux/files/home/go
 set GOROOT /data/data/com.termux/files/usr/lib/go
@@ -99,7 +105,7 @@ alias bat="bat -f --theme 'Visual Studio Dark+'"
 CONF
 
 git config --global core.autocrlf
-[[ -e ${PREFIX}/etc/fish/config.fish ]] && rm -rf ${PREFIX}/etc/fish/config.fish
+[[ -L ${PREFIX}/etc/fish/config.fish ]] || rm -rf ${PREFIX}/etc/fish/config.fish
 ln -s ${HOME}/.local/etc/fish/config.fish ${PREFIX}/etc/fish/config.fish 2>>$LOGFILE
 sed -i '12a chsh -s fish' ${PREFIX}/etc/bash.bashrc
 
@@ -109,16 +115,19 @@ export LD_LIBRARY_PATH=${PREFIX}/lib:${HOME}/.local/lib
 echo -en "\e[33mWARNING:\e[0m You are out of i-Haklab | Some commands and tools could not be running.\n"
 CONF
 
-echo -en $Y"""W:$W Now you will see a PS1 as '⋊> ~/i-Haklab on master ⨯'
-   when it happen hold on for one minute and then type$Y exit$W to$W continue$W
-"""
-fish <(curl -fsSL "$iHDB/.local/etc/i-Haklab/get.oh-my.fish") 2>>$LOGFILE
-TMP_fish=$(mktemp)
-cat <<- CONF > $TMP_fish
+[[ -e ${HOME}/.config/fish/conf.d/omf.fish ]] || {
+	echo -en $Y"""W:$W Now you will see a PS1 as '⋊> ~/i-Haklab on master ⨯'
+	   when it happen hold on for one minute and then type$Y exit$W to$W continue$W
+	""";
+	fish <(curl -fsSL "$iHDB/.local/etc/i-Haklab/get.oh-my.fish") 2>>$LOGFILE;
+}
+file=$(mktemp)
+cat <<- CONF > $file
 #!/bin/env fish
 omf install bira
 CONF
-fish $TMP_fish 2>>$LOGFILE
+fish $file 2>>$LOGFILE
+rm $file
 
 echo "Updating mlocate data base ..."
 updatedb
