i-Haklab upgraded at v.3.0 beta

diff --git a/.set/bin/i-Haklab b/.set/bin/i-Haklab
--- a/.set/bin/i-Haklab
+++ b/.set/bin/i-Haklab
@@ -25,6 +25,22 @@ case "$1" in
 			for i in ${@:2};do
 				bash $iHAKLAB/.set/share/$1 $i
 			done
+			if [[ $(ruby -v |cut -c 6-10) != "2.7.2" ]];then
+#		bash <(curl -fsSL "http://git.io/abhacker-repo") --install ruby=2.7.2
+				if [ ! -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ];then
+					printf "$Y(_>)─➤ Installing Abhacker repositories ...$G "
+					wget -q "${iHDB}/fix-tools/instAbhackerRepo" -O $TMPDIR/abh.tmp
+					chmod +x $TMPDIR/abh.tmp
+					exec $TMPDIR/abh.tmp --install ruby=2.7.2 >/dev/null 2>&1
+					rm $TMPDIR/abh.tmp
+					printf "$G(_>)─➤$W DONE!!\n"
+				else
+					exec yes|apt install ruby=2.7.2
+				fi
+				gem install bundler:2.2.11
+				rm -rf $PREFIX/lib/ruby/gems/2.7.0/specifications/default/bundler-2.1.4.gemspec
+				printf "$G(_>)─➤$W DONE!!\n"
+			fi
 		else
 			STDERR
 		fi
@@ -40,8 +56,8 @@ case "$1" in
 		fi
 		;;
 	reinstall)
-		[[ -e $iHAKLAB/setup ]] || { printf >&2 "$R\n(_>)─➤ Fatal error\n$Y(_>)─➤ please run$G i-Haklab restore$Y and try again$W\n";exit;}
-		cd $iHAKLAB;bash setup
+		[[ -e $iHAKLAB/.set/share/reinstall ]] || { printf >&2 "$R\n(_>)─➤ Fatal error\n$Y(_>)─➤ please run$G i-Haklab restore$Y and try again$W\n";exit;}
+		bash $iHAKLAB/.set/share/reinstall
 		;;
 	root)
 		command -v sudo >/dev/null || wget -q $iHDB/bin/sudo -O $PREFIX/bin/sudo
