upgraded at version 3.0beta

diff --git a/.set/bin/i-Haklab b/.set/bin/i-Haklab
--- a/.set/bin/i-Haklab
+++ b/.set/bin/i-Haklab
@@ -1,357 +1,121 @@
-#!/data/data/com.termux/files/usr/bin/bash
-#Created on Dec/2018
+#!/usr/bin/bash
+#Created on Dec/2018 and upgraded on Ago/2021 by @Ivam3
 IFS=$'\n\t'
 trap ctrl_c 2
-
-if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
-	iHAKLAB=/data/data/com.termux/files/home/i-Haklab
-elif [ -d /data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab ]; then
-        iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
-else
-	chk-iHaklab
-fi
-
-source $iHAKLAB/.set/libexec/colors 
-source $iHAKLAB/.set/var/variables
+source $PREFIX/share/i-Haklab/.set/var/variables
 source $iHAKLAB/.set/functions/functions
-ctrl_c() { k-boom;}
+ctrl_c(){ printf "$Y\n\n\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n\n";exit;}
+chk-iHaklab
 chk-Cuser
-
-if [ "$CHECKROOT" = "root" ]; then
-	LPORT=80
-else
-	LPORT=4546
-fi
-banner
-if [ -z $1 ] || [ $1 = help ]; then
-	Menu
-
-elif [ $1 = list ]; then
-	printf "$TOOL"
-
-elif [ $1 = show ] && [ -z $2 ]; then
-        printf "$R[w]─➤$W Argument show need an option\n"
-elif [ $1 = show ] && [ $2 ]; then
-	if [ "$README_TOOL" = $2 ]; then
-		cat $iHAKLAB/.set/libexec/Readme/$2
-		echo
-	elif [ $2 = books ]; then
-		cat $iHAKLAB/.set/libexec/Books/List | awk '{print $1,$2}'
-		printf "$Y\n[?]─➤$W Type the book's number or press$R enter$W to exit\n"
-		while read -p "[+]─➤ " ANSW && [ -z $ANSW ]; do
-			exit
-		done
-		if [ ! -z $ANSW ]; then
-			BOOK=$(cat -n $iHAKLAB/.set/libexec/Books/List | grep $ANSW | awk '{print $NF}')
-			if [ ! -z $BOOK ]; then
-				chk-mega
-				megadl https://mega.nz/$BOOK
-			else
-				printf "$R[w]─➤$W Unable to locate option $ANSW\n"
-				exit
-			fi
-		fi
-	elif [ $2 = tutorials ]; then
-		exec bash $iHAKLAB/.set/share/tutorials
-	elif [ $2 = QG ]; then
-		if [ -d $iHAKLAB/QuickGuides ]; then
-			ls $iHAKLAB/QuickGuides
-			printf "$Y\n[?]─➤$W Type QG name or press$R enter$W to exit\n"
-			while read -p "[+]─➤ " ANSW && [ -z $ANSW ]; do
-				exit
+[ $# -eq 0 ] && { printf >&2 "$R(_>)─➤$W missing argument, type $(basename $0) -h for help";exit;}
+STDERR(){ printf "$R(_>)─➤$W missing argument, type $(basename $0) -h for help";exit;}
+clear;banner
+case "$1" in
+	-h|help)
+		Menu
+		;;
+	-v|version)
+		printf "$G(_>)─➤$W i-Haklab $(grep -om 1 "v.*.*" $iHAKLAB/README.md|awk '{print $1}') 2021 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3."
+		;;
+	about)
+		[[ $2 ]] && cat $iHAKLAB/.set/libexec/Readme/$2 || STDERR
+		;;
+	install|remove)
+		if [[ $2 ]];then
+			for i in ${@:2};do
+				bash $iHAKLAB/.set/share/$1 $i
 			done
-			if [ -e $iHAKLAB/QuickGuides/$ANSW ]; then
-				exec bash $iHAKLAB/QuickGuides/$ANSW
-			else
-				printf "$R[w]─➤$W Unable to locate QG $ANSW\n"
-			fi
 		else
-			printf "$R[w]─➤$W Quick Guides was removed$R |$W please install it\n"
+			STDERR
 		fi
-	elif [ $2 = games ]; then
-		exec bash $iHAKLAB/.set/share/games $3 $@
-	else
-		printf "$R[w]─➤$W Unable to locate option $2\n"
-	fi
-
-
-elif [ $1 = install ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument install need an option\n"
-elif [ $1 = install ] && [ $2 ]; then
-	TOOL=$(ls $iHAKLAB/.set/to-install/ | grep -iv .zip | grep $2)
-	if [ "$TOOL" = $2 ]; then
-		bash $iHAKLAB/.set/to-install/$TOOL
-	else
-		printf "$R[w]─➤$W Unable to locate tool $2\n"
-		sleep 1
-		printf "$G[i]─➤$W Trying with apptitude repositories . . .\n"
-		sleep 1
-		apt install $2 -y
-	fi
-	if [ $(ruby -v |cut -c 6-10) == "3.0.0" ] && [ -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ];then
-		printf "$Y[!]─➤$W downgrading ruby to 2.7.2..."
-		yes|apt install ruby=2.7.2 >/dev/null 2>&1
-		printf "$G DONE!!$W\n"
-	fi
-
-
-elif [ $1 = remove ] && [ -z $2 ]; then
-        printf "$R[w]─➤$W Argument remove need an option\n"
-elif [ $1 = remove ] && [ $2 ]; then
-        TOOL=$(ls $iHAKLAB/.set/to-remove | grep -iv .zip | grep $2)
-        if [ "$TOOL" = $2 ]; then
-		bash $iHAKLAB/.set/to-remove/$TOOL
-		k-boom
-	elif [ -e $PREFIX/bin/$2 ]; then
-		apt remove $2 -y
-		apt autoremove -y
-		k-boom
-	else
-		printf "$R[w]─➤$W Unable to locate tool/framework $2\n"
-	fi
-
-
-elif [ $1 = weechat ]; then
-	if [ ! -e $PREFIX/bin/weechat ]; then
-		apt install weechat -y
-	fi
-	printf "$Y\n   [!]->$W After start weechat type the next commands$Y <-[!]$Y\n/server add freenode chat.freenode.net/6697 -ssl -autoconnect\n    /set irc.server.freenode.autojoin #Ivam3byCinderella\n                   /connect freenode\n                  /nick your-nickname\n               /join #Ivam3byCinderella$G\n               $R[w]-> USE SOME VPN <-[w]$G\n\n                 Press enter to start$W\n"
-	read enter
-	weechat
-	k-boom
-
-
-elif [ $1 = root ]; then
-	command -v proot > /dev/null || pkg install proot -y > /dev/null 
-	proot -0 -w ~ $PREFIX/bin/fish
-
-
-elif [ $1 = speedtest ]; then
-	command -v python > /dev/null 2>&1 || apt install python -y /dev/null 2>&1
-	command -v speedtest-cli > /dev/null 2>&1 || python -m pip install speedtest-cli /dev/null 2>&1
-	printf "$Y[!]─➤$W Running speed test . . .$G\n"
-	speedtest-cli --simple
-	printf "$W"
-
-elif [ $1 = update ]; then
-	TMP_FILE=$(mktemp)
-	curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/upgrade -o $TMP_FILE > /dev/null 2>&1
-	RMONTH=$(grep "Modify" $TMP_FILE | cut -d "-" -f2)
-	RDAY=$(grep "Modify" $TMP_FILE | cut -d "-" -f3)
-	LMONTH=$(stat $iHAKLAB | grep Modify | awk '{print $2}' | cut -d "-" -f2)
-	LDAY=$(stat $iHAKLAB | grep Modify | awk '{print $2}' | cut -d "-" -f3)
-
-	if [ $LMONTH -eq $RMONTH ]; then
-		if [ $LDAY -gt $RDAY ]; then
-			printf "$G\n[i]─➤$W Already up to date$G <-[i]$W\n"
+		;;
+	restore)
+		printf "$Y(_>)─➤$W Restoring (It could take a while)..";
+		rm -rf $iHAKLAB
+		git clone --quiet https://github.com/Ivam3/i-Haklab.git $iHAKLAB
+		if [[ -d $iHAKLAB ]];then
+			printf "$G. DONE!!$W\n"
 		else
-			printf "$Y[!]─➤$W Upgrading (It could take a while) ...\n"
-			rm -rf $iHAKLAB > /dev/null 2>&1
+			printf "$R\n(_>)─➤ ERR_restore";ctrl_c
+		fi
+		;;
+	reinstall)
+		[[ -e $iHAKLAB/setup ]] || { printf >&2 "$R\n(_>)─➤ Fatal error\n$Y(_>)─➤ please run$G i-Haklab restore$Y and try again$W\n";exit;}
+		cd $iHAKLAB;bash setup
+		;;
+	root)
+		command -v sudo >/dev/null || wget -q $iHDB/bin/sudo -O $PREFIX/bin/sudo
+		exec sudo root
+		;;
+	show)
+		[[ $2 ]] && bash $iHAKLAB/.set/share/$1 ${@:2} || STDERR
+		;;
+	speedtest)
+		command -v python >/dev/null || yes|apt install python >/dev/null 2>&1
+		command -v speedtest-cli >/dev/null || python -m pip install --no-color --quiet --no-cache-dir speedtest-cli
+		printf "$Y(_>)─➤$W Running speed test.\n"
+		speedtest-cli
+		;;
+	update)
+		TMP_FILE=$(mktemp)
+		wget -q $iHDB/share/upgrade -O $TMP_FILE
+		RMONTH=$(grep "Modify" $TMP_FILE | cut -d "-" -f2)
+		RDAY=$(grep "Modify" $TMP_FILE | cut -d "-" -f3)
+		LMONTH=$(stat $iHAKLAB | grep Modify | awk '{print $2}' | cut -d "-" -f2)
+		LDAY=$(stat $iHAKLAB | grep Modify | awk '{print $2}' | cut -d "-" -f3)
+		Done(){ printf "$G\n(_>)─>$W Already up to date$G <-(<_)$W\n";}
+		if [[ $LMONTH -eq $RMONTH ]];then
+			if [[ $LDAY -gt $RDAY ]];then
+				Done
+			else
+				printf "$Y(_>)─➤$W Upgrading (It could take a while)...\n"
+				rm -rf $iHAKLAB
+				git clone --quiet https://github.com/Ivam3/i-Haklab.git $iHAKLAB
+				if [ -d $iHAKLAB ];then
+					bash $TMP_FILE
+					Done
+				else
+					k-boom
+				fi
+			fi
+		elif [ $LMONTH -gt $RMONTH ]; then
+			Done
+		else
+			printf "$Y(_>)─➤$W Upgrading (It could take a while)...\n"
+			rm -rf $iHAKLAB
 			while [ ! -d $iHAKLAB ]; do
-				git clone https://github.com/Ivam3/i-Haklab.git $iHAKLAB > /dev/null 2>&1
+				git clone --quiet https://github.com/Ivam3/i-Haklab.git $iHAKLAB
 			done
 			if [ -d $iHAKLAB ]; then
 				bash $TMP_FILE
-				printf "$G\n[i]─>$W Already up to date$G <-[i]$W\n"
+				Done
 			else
-				ctrl_c
+				k-boom
 			fi
 		fi
-	elif [ $LMONTH -gt $RMONTH ]; then
-		printf "$G\n[i]->$W Already up to date$G <-[i]$W\n"
-	else
-		printf "$Y[!]─➤$W Upgrading (It could take a while) ...\n"
-		rm -rf $iHAKLAB > /dev/null 2>&1
-		while [ ! -d $iHAKLAB ]; do
-			git clone https://github.com/Ivam3/i-Haklab.git $iHAKLAB > /dev/null 2>&1
-		done
-		if [ -d $iHAKLAB ]; then
-			bash $TMP_FILE
-			printf "$G\n[i]->$W Already up to date$G <-[i]$W\n"
+		rm $TMP_FILE
+		;;
+	weechat)
+		[[ -e $PREFIX/bin/weechat ]] || yes|apt install weechat
+		printf "$Y\n   (_>)─>$W After start weechat type the next commands$Y <─(<_)$Y\n/server add freenode chat.freenode.net/6697 -ssl -autoconnect\n    /set irc.server.freenode.autojoin #Ivam3byCinderella\n                   /connect freenode\n                  /nick your-nickname\n               /join #Ivam3byCinderella$G\n               $R(w)-> USE SOME VPN <-(w)$G\n\n                 Press enter to start$W\n"
+		read enter;weechat;k-boom
+		;;
+#:::AUTOMATED COMMAND:::#
+	bf|forwarding)
+		bash $iHAKLAB/.set/share/$1 ${@}
+		;;
+	payapk|payexe|paypdf|shodan)
+		if [ -z $2 ] || [ $2 -a "$3" -eq "$3" ] 2>/dev/null
+		then
+			bash $iHAKLAB/.set/share/msf ${@}
 		else
-			ctrl_c
+			STDERR
 		fi
-	fi
-	rm $TMP_FILE
-
-
-elif [ $1 = restore ]; then
-	printf "$Y[!]─➤$W Restoring (It could take a while) ...\n"
-        rm -rf $iHAKLAB > /dev/null 2>&1
-	while [ ! -d $iHAKLAB ]; do
-		git clone https://github.com/Ivam3/i-Haklab.git $iHAKLAB > /dev/null 2>&1
-        done
-        if [ -d $iHAKLAB ]; then
-		printf "$G[*]─➤$W DONE!!\n"
-        else
-		ctrl_c
-        fi
-
-
-elif [ $1 = reinstall ]; then
-	if [ -e $iHAKLAB/.set/libexec/reinstall ]; then
-		bash $iHAKLAB/.set/libexec/reinstall
-	else
-		printf "$R\n[w]─➤ Fatal error\n$Y[!] please run$G i-Haklab restore$Y and try again$W\n"
-		exit
-	fi
-
-
-elif [ $1 = version ]; then
-	cat $iHAKLAB/README.md | grep -o v.*.*.9 | awk '{print $1}'
-
-
-elif [ $1 = share ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument share need an option\n"
-elif [ $1 = share ] && [ $2 ] && [ -z $3 ]; then
-	if [ $2 = upload ]; then
-		printf "$R[w]─➤$W specify a file to share\n"
-	elif [ $2 = download ]; then 
-		printf "$R[w]─➤$W specify file link\n"
-	else
-		printf "$R[w]─➤$W Invalid option: $2\n"
-	fi
-elif [ $1 = share ] && [ $2 ] && [ $3 ]; then
-	chk-ffsend
-	bash $iHAKLAB/.set/share/share ${@:2}
-
-
-elif [ $1 = apk ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument apk need an option\n"
-elif [ $1 = apk ] && [ $2 ]; then
-	if [ $2 = inlan ]; then
-		chk-msf
-		bash $iHAKLAB/.set/share/apk_inlan
-	elif [ $2 = outlan ] && [ -z $3 ]; then
-		printf "$R[w]─➤$W Argument outlan need a server as an option"
-	elif [ $2 = outlan ] && [ $3 ]; then
-		chk-msf
-		bash $iHAKLAB/.set/share/apk_outlan $3
-	else
-		printf "$R[w]─➤$W invalid option\n"
-	fi
-
-
-elif [ $1 = payexe ] && [ -z $2 ]; then
-        printf "$R[w]─➤$W Argument payexe need an option\n"
-elif [ $1 = payexe ] && [ $2 ]; then
-        if [ $2 = inlan ]; then
-                chk-msf
-		bash $iHAKLAB/.set/share/payexe_inlan
-	elif [ $2 = outlan ] && [ -z $3 ]; then
-		printf "$R[w]─➤$W Argument outlan need a server as an option"
-	elif [ $2 = outlan ] && [ $3 ]; then
-		chk-msf
-		bash $iHAKLAB/.set/share/payexe_outlan $3
-	else
-                printf "$R[w]─➤$W invalid option\n"
-        fi
-
-
-elif [ $1 = paylink ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument paylink need an option and target\n"
-elif [ $1 = paylink ] && [ $2 = pc ] && [ -z $3 ]; then
-	printf "$R[w]─➤$W Option pc need a target\n"
-elif [ $1 = paylink ] && [ $2 = pc ] && [ $3 ]; then
-	bash $iHAKLAB/.set/share/paylink_pc $2 $3
-elif [ $1 = paylink ] && [ $2 = nexam ] && [ -z $3 ]; then
-        printf "$R[w]─➤$W Option nexam need a target\n"
-elif [ $1 = paylink ] && [ $2 = nexam ] && [ $3 ]; then
-	bash $iHAKLAB/.set/share/paylink_nexam $2 $3
-elif [ $1 = paylink ] && [ $2 = soa5 ]; then
-	bash $iHAKLAB/.set/share/paylink_soa5 $2
-
-
-elif [ $1 = forwarding ] && [ -z $2 ]; then
-	chk-ssh
-	bash $iHAKLAB/.set/share/forwarding_default
-elif [ $1 = forwarding ] && [ $2 ] && [ -z $3 ]; then
-	chk-ssh
-	bash $iHAKLAB/.set/share/forwarding_port $2
-elif [ $1 = forwarding ] && [ $2 ] && [ $3 ]; then
-	chk-ssh
-	bash $iHAKLAB/.set/share/forwarding_dns $2 $3
-
-
-elif [ $1 = handler ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument handler need an option$R |$W use one of those:\n"
-	if [ -d ~/java/handler ]; then
-		ls ~/java/handler | grep .rc | sort
-	else
-		printf "$R[w]─➤$W The handler box is empty\n"
-	fi
-elif [ $1 = handler ] && [ $2 ]; then
-	if [ -e ~/java/handler/$2 ]; then
-		if [ $CHECKROOT = "root" ]; then
-			banner
-			chk-sudo
-			chk-msf
-			sudo msfconsole -q -r ~/java/handler/$2
-		else 
-			banner
-			chk-msf
-			msfconsole -q -r ~/java/handler/$2
-		fi
-	else
-		printf "$R[w]─➤$W File $2 doesn't exist\n"
-	fi
-
-
-elif [ $1 = shodan ]; then
-	chk-msf
-	bash $iHAKLAB/.set/share/shodan
-
-
-elif [ $1 = paypdf ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument paypdf need a pdf file name\n"
-elif [ $1 = paypdf ] && [ $2 ]; then
-	chk-msf
-	bash $iHAKLAB/.set/share/paypdf $2
-
-
-elif [ $1 = bfmail ] && [ -z $2 ]; then
-        printf "$R[w]─➤$W Argument bfmail need a mail/victim as option 1$G\n[ex]->$W i-Haklab bfmail victim@gmail.com passwords.txt"
-elif [ $1 = bfmail ] && [ $2 ] && [ -z $3 ]; then
-        printf "$R[w]─➤$W Argument bfmail need a passwords file as option 2$G\n[ex]->$W i-Haklab bfmail victim@hotmail.com passwords.txt"
-elif [ $1 = bfmail ] && [ $2 ] && [ $3 ]; then
-	bash $iHAKLAB/.set/share/bfmail $2 $3
-
-
-elif [ $1 = bfftp ] && [ -z $2 ]; then
-        printf "$R[w]─➤$W Argument bfftp need a users file as option 1$G\n[ex]->$W i-Haklab bfftp users.txt passwords.txt 0.0.0.0"
-elif [ $1 = bfftp ] && [ $2 ] && [ -z $3 ]; then
-        printf "$R[w]─➤$W Argument bfftp need a passwords file as option 2$G\n[ex]->$W i-Haklab bfftp users.txt passwords.txt 0.0.0.0"
-elif [ $1 = bfftp ] && [ $2 ] && [ $3 ] && [ -z $4 ]; then
-        printf "$R[w]─➤$W Argument bfftp need an ip/victim as option 3$G\n[ex]->$W i-Haklab bfftp users.txt passwords.txt 0.0.0.0"
-elif [ $1 = bfftp ] && [ $2 ] && [ $3 ] && [ $4 ]; then
-        if [ ! -e $2 ]; then
-                printf "$R[w]─➤$W File for users not found"
-        elif [ ! -e $3 ]; then
-                printf "$R[w]─➤$W File for passwords not found"
-        elif [ -e $2 ] && [ -e $3 ]; then
-                printf "$R[w]─> USE SOME VPN <-[w]$W\n  press$G enter$W to start"
-                read enter
-		chk-hydra
-                hydra -L $2 -P $3 $4 ftp
-	else
-		ctrl_c
-        fi
-
-
-#elif [ $1 = phishing ] && [ -z $2 ];then
-#	printf "$R[w]─➤$W Argument phishing needs a website as an option1"
-#elif [ $1 = phishing ] && [ $2 ] && [ -z $3 ]; then
-#	printf "$R[w]─➤$W Argument phishing needs a redirection as an option2"
-#elif [ $1 = phishing ] && [ $2 ] && [ $3 ]; then
-#	bash $iHAKLAB/.set/share/phishing $2 $3
-
-
-elif [ $1 = ESmsg ] && [ -z $2 ]; then
-	printf "$R[w]─➤$W Argument ESmsg need an option"
-elif [ $1 = ESmsg ] && [ $2 ]; then
-	bash $iHAKLAB/.set/share/ESmsg $2
-
-else
-	printf "$R[w]─➤$W Invalid argument $1 $R|$W Use help as argument to main menu\n"
-fi
-#			@IVAM3
+		;;
+	share|Esmsg)
+		[[ $2 ]] && bash $iHAKLAB/.set/share/$1 ${@:2} || STDERR
+		;;
+	*)
+		STDERR
+		;;
+esac
diff --git a/.set/fix-tools/RuGiR b/.set/fix-tools/RuGiR
--- a/.set/fix-tools/RuGiR
+++ b/.set/fix-tools/RuGiR
@@ -12,47 +12,49 @@ B='\033[1;34m'
 M='\033[1;35m'
 C='\033[1;36m'
 W='\033[0m'
+RUBYv=$(ls $PREFIX/lib/ruby |grep -m 1 '[0-9].[0-9].[0-9]')
 iHDB="https://github.com/ivam3/i-Haklab/raw/master/.set"
 command -v ruby >/dev/null || apt install ruby -y >/dev/null 2>&1
 command -v lolcat >/dev/null || gem install lolcat >/dev/null 2>&1
 ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}
 Banner(){ clear;printf "\n ____         ____ _ ____\n|  _ \ _   _ / ___(_)  _ \ \n| |_) | | | | |  _| | |_) |\n|  _ <| |_| | |_| | |  _ <\n|_| \_|\__,_|\____|_|_| \_|v.2\n#::Ruby Gems Issues Resolved::#\n #::: @Ivam3byCinderella ::::#\n";sleep 1;}
 Banner|lolcat
-printf "$G\n[¿]─>$W Choose an option $G<-[?]\n\n{01}$W$Y[MSFCONSOLE]─➤$W CANNOT LINK EXECUTABLE \"ruby\":$Y\n\t╰────────➤$W library \"/data/da..../bigdecimal.so\" not found$G\n{02}$W$Y[GRPC.GEMSPEC]─➤$W There was an error parcing Gemfile$G\n{03}$W$Y[GEMS]─➤$W Could not find <gem's name> in any of the sources$G\n{04}$Y[BIGDECIMAL]─➤$W Gem bigdecimal architecture compatibility$G\n{99}$R[EXIT]\n\n$W";read -p "{ANSW}-> " ANSW
+printf "$G\n[¿]─>$W Choose an option $G<-[?]\n\n{01}$W$Y[MSFCONSOLE]─➤$W CANNOT LINK EXECUTABLE \"ruby\":$Y\n\t╰────────➤$W library \"/data/da..../bigdecimal.so\" not found$G\n{02}$W$Y[GRPC.GEMSPEC]─➤$W There was an error parcing Gemfile$G\n{03}$W$Y[GEMS]─➤$W Could not find <gem's name> in any of the sources$G\n{04}$Y[BIGDECIMAL]─➤$W Gem bigdecimal architecture compatibility$G\n{05}$Y[BUNDLER]─➤$W You have already activated bundler 2.1.4, but your Gemfile requires bundler 2.2.11$G\n{99}$R[EXIT]\n\n$W";read -p "{ANSW}-> " ANSW
 case $ANSW in
 	01|1)
-		RUBYv=$(ls $PREFIX/lib/ruby |grep -m 1 '[0-9].[0-9].[0-9]')
 		BIGDECIMAL=$(find $PREFIX/lib/ruby/${RUBYv} -iname "bigdecimal.so")
-echo "#!/data/data/com.termux/files/usr/bin/sh" > $PREFIX/bin/msfconsole
-echo "SCRIPT_NAME=\$(basename \"\$0\")" >> $PREFIX/bin/msfconsole
-echo "METASPLOIT_PATH=\"\${PREFIX}/opt/metasploit-framework\"" >> $PREFIX/bin/msfconsole
-echo "# Fix ruby bigdecimal extensions linking error." >> $PREFIX/bin/msfconsole
-echo "export LD_PRELOAD=\"${BIGDECIMAL}:\$LD_PRELOAD\"" >> $PREFIX/bin/msfconsole
-echo "case \"\$SCRIPT_NAME\" in" >> $PREFIX/bin/msfconsole
-echo "	msfconsole)" >> $PREFIX/bin/msfconsole
-echo "		if [ ! -d \"$PREFIX/var/lib/postgresql\" ];then" >> $PREFIX/bin/msfconsole
-echo "			mkdir -p \"$PREFIX/var/lib/postgresql\"" >> $PREFIX/bin/msfconsole
-echo "			initdb \"${PREFIX}/var/lib/postgresql\"" >> $PREFIX/bin/msfconsole
-echo "		fi" >> $PREFIX/bin/msfconsole
-echo "		if ! pg_ctl -D \"${PREFIX}/var/lib/postgresql\" status > /dev/null 2>&1; then" >> $PREFIX/bin/msfconsole
-echo "			pg_ctl -D \"${PREFIX}/var/lib/postgresql\" start --silent" >> $PREFIX/bin/msfconsole
-echo "		fi" >> $PREFIX/bin/msfconsole
-echo "		if [ -z \"\$(psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='msf'\")\" ];then" >> $PREFIX/bin/msfconsole
-echo "			createuser msf" >> $PREFIX/bin/msfconsole
-echo "		fi" >> $PREFIX/bin/msfconsole
-echo "		if [ -z \"\$(psql -l | grep msf_database)\" ];then" >> $PREFIX/bin/msfconsole
-echo "			createdb msf_database" >> $PREFIX/bin/msfconsole
-echo "		fi" >> $PREFIX/bin/msfconsole
-echo "		exec ruby \"\$METASPLOIT_PATH/\$SCRIPT_NAME\" \"\$@\"" >> $PREFIX/bin/msfconsole
-echo "		;;" >> $PREFIX/bin/msfconsole
-echo "	msfd|msfrpc|msfrpcd|msfvenom)" >> $PREFIX/bin/msfconsole
-echo "		exec ruby \"\$METASPLOIT_PATH/\$SCRIPT_NAME\" \"\$@\"" >> $PREFIX/bin/msfconsole
-echo "		;;" >> $PREFIX/bin/msfconsole
-echo "	*)" >> $PREFIX/bin/msfconsole
-echo "		echo \"[!] Unknown Metasploit command '\$SCRIPT_NAME'.\"" >> $PREFIX/bin/msfconsole
-echo "		exit 1" >> $PREFIX/bin/msfconsole
-echo "		;;" >> $PREFIX/bin/msfconsole
-echo "esac" >> $PREFIX/bin/msfconsole
+		cat <<- CONF > $PREFIX/bin/msfconsole
+#!/data/data/com.termux/files/usr/bin/sh
+SCRIPT_NAME=\$(basename "\$0")
+METASPLOIT_PATH="${PREFIX}/opt/metasploit-framework"
+# Fix ruby bigdecimal extensions linking error.
+export LD_PRELOAD="${BIGDECIMAL}:\$LD_PRELOAD"
+case "\$SCRIPT_NAME" in
+        msfconsole)
+                if [ ! -d "$PREFIX/var/lib/postgresql" ];then
+                        mkdir -p "$PREFIX/var/lib/postgresql"
+                        initdb "${PREFIX}/var/lib/postgresql"
+                fi
+                if ! pg_ctl -D "${PREFIX}/var/lib/postgresql" status > /dev/null 2>&1; then
+                        pg_ctl -D "${PREFIX}/var/lib/postgresql" start --silent
+                fi
+                if [ -z "\$(psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='msf'")" ];then
+                        createuser msf
+                fi
+                if [ -z "\$(psql -l | grep msf_database)" ];then
+                        createdb msf_database
+                fi
+                exec ruby "\$METASPLOIT_PATH/\$SCRIPT_NAME" "\$@"
+                ;;
+        msfd|msfrpc|msfrpcd|msfvenom)
+                exec ruby "\$METASPLOIT_PATH/\$SCRIPT_NAME" "\$@"
+                ;;
+        *)
+                echo "[!] Unknown Metasploit command '\$SCRIPT_NAME'."
+                exit 1
+                ;;
+esac
+CONF
 		chmod +x $PREFIX/bin/msfconsole
 		ln -sf $(which msfconsole) $PREFIX/bin/msfvenom
 		;;
@@ -60,19 +62,18 @@ echo "esac" >> $PREFIX/bin/msfconsole
 		yes|pkg clean && pkg autoclean && pkg autoremove && pkg update --fix-missing && pkg --configure -a && pkg update --fix-missing && pkg upgrade && pkg install clang
 		;;
 	03|3)
-		while read -p " [Gems name]─➤ " GEM && [ -z $GEM ];do
+		while read -p " (Gems name)─➤ " GEM && [ -z $GEM ];do
 			ctrl_c
 		done
-		while read -p " [Version]─➤ " GEMv && [ -z $GEMv ];do
+		while read -p " (Version)─➤ " GEMv && [ -z $GEMv ];do
 			GEMv=">= 0.1"
 		done
-		while read -p " [Gemfile path]─➤ " GEMfile && [ -z $GEMfile ];do
+		while read -p " (Gemfile path)─➤ " GEMfile && [ -z $GEMfile ];do
 			ctrl_c
 		done
 		gem install bundler
 		gem install $GEM -v "$GEMv" -- --using-system-libraries
 		bundle config build.$GEM -- using-system-libraries
-		RUBYv=$(ls $PREFIX/lib/ruby |grep -m 1 '[0-9].[0-9].[0-9]')
 		RUBYext=$(find $PREFIX/lib/ruby/gems/${RUBYv}/extensions -iname "${GEM}-${GEMv}")
 		echo "$RUBYext" >> Gemfile.local
 		sed '/rbnacl/d' -i Gemfile.lock
@@ -84,6 +85,18 @@ echo "esac" >> $PREFIX/bin/msfconsole
 		;;
 	04|4)
 		curl -Ls ${iHDB}/fix-tools/fixbigdecimal|bash
+		;;
+	05|5)
+		while read -p "(_>)_Version_to_remove_{ex_2.1.4}─➤ " OLDv && [ -z $OLDv ];do
+			continue
+		done
+		while read -p "(_>)_Version_to_install_{ex_2.2.11}─➤ " NEWv && [ -z $NEWv ];do
+			continue
+		done
+		gem install bundler:$NEWv
+		if [ -e $PREFIX/lib/ruby/gems/$RUBYv/specifications/default/bundler-$OLDv.gemspec ];then
+			rm $PREFIX/lib/ruby/gems/$RUBYv/specifications/default/bundler-$OLDv.gemspec
+		fi
 		;;
 	*)
 		ctrl_c
diff --git a/.set/functions/functions b/.set/functions/functions
--- a/.set/functions/functions
+++ b/.set/functions/functions
@@ -1,11 +1,7 @@
 #!/bin/bash
 # This file contain all i-Haklab functions
 
-if [ -d /data/data/com.termux/files/home/i-Haklab ]; then
-	iHAKLAB=/data/data/com.termux/files/home/i-Haklab
-else
-	iHAKLAB=/data/data/com.termux/files/home/storage/external-1/roothome/i-Haklab
-fi
+iHAKLAB=/data/data/com.termux/files/usr/share/i-Haklab
 
 banner() {
 	if [ ! -e $iHAKLAB/.set/libexec/banner/i-Haklab ]; then
@@ -16,44 +12,6 @@ banner() {
 }
 export -f banner
 
-chk-iHaklab() {
-	until [ -d $iHAKLAB ]; do
-		printf "$R\n[W]:-> i-Haklab needed$W |$Y Do y ou wanna install it?$W\n"
-        	while read -p "[yes/no]:-> " yesorno && [ -z $yesorno ]; do
-                	continue
-        	done
-        	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
-                	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
-                	cd ~/i-Haklab;bash setup-lite
-        	else
-                	printf "$G\n[!]-> Have a nice hacking day!!\n\n"
-                	exit
-        	fi
-	done
-}
-export -f chk-iHaklab
-
-ctrl_c() {
-	printf "$Y\n[!]$R Need a help? join to$B Telegram$R t.me/Ivam3_Bot$W\n"
-}
-export -f ctrl_c
-
-chk-Cuser() {
-	while [ ! $(id -u) -ne 0 ]; do
-        	printf "$R\n[W]:-> You need to be a common user$W\n"
-        	exit
-	done
-}
-export -f chk-Cuser
-
-chk-Ruser() {
-	while [ ! $(id -u) -eq 0 ]; do
-		printf "$R\n[W]:-> You need to be a root user$W\n"
-		exit
-	done
-}
-export -f chk-Ruser
-
 k-boom() {
 	if [ ! -e $iHAKLAB/.set/libexec/banner/k-boom ]; then
 		wget https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/banner/k-boom -O $iHAKLAB/.set/libexec/banner/k-boom > /dev/null 2>&1
@@ -62,105 +20,97 @@ k-boom() {
 }
 export -f k-boom
 
-Menu() {
-	printf "$Y\n[i]->$W i-Haklab v.2.0 (c) 2020 by Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. If the law is violated with it's use, this would be the responsibility of the user who handled it.\n$Y\nSyntax:$W i-Haklab [-arg-] [-option-]\n
-$Y Arguments$W  |$Y    Options$W     |$Y    Description$W
-╰─help─────➤────────────────➤ Show this help menu
-╰─list─────➤────────────────➤ List all available tools/frameworks
-╰─show─────➤──tools/books───➤ Show details about specific tools/books
-|   ╰───────────|─────|─────➤ availables to be downloaded
-|   |           ╰─────|─────➤ ex : i-Haklab show bettercap
-|   |                 ╰─────➤ ex : i-Haklab show books
-|   ╰──────➤──tutorials/QG──➤ Show tutorials and Quick Guides availables
-|   ╰──────➤─────games──────➤ Show games available for play
-╰─install──➤───tool─name────➤ Install tools or frameworks
-╰─remove───➤───tool─name────➤ Remove tools or frameworks
-╰─weechat──➤────────────────➤ Connect with irc Ivam3byCinderella chat
-╰─update───➤────────────────➤ Update i-Haklab
-╰speedtest─➤────────────────➤ Run a speed test of your network
-╰─root─────➤────────────────➤ Simulates a super user environment
-╰─restore──➤────────────────➤ Restore the main directory to fix some bugs
-╰reinstall─➤────────────────➤ Reinstall i-Haklab to factory configurations
-╰─version──➤────────────────➤ Show i-Haklab version installed
-|          |       |        |
-|          |       |        |
-  $Y [--] Automatitation Arguments [--]$W
- Arguments |    Options     |    Description
-|───apk────➤──inlan/outlan──➤ Create a coded payload apk
-|    |          ╰─────|─────➤ LPORT=4546 apk=inlan.apk
-|    |                ╰─────➤ LPORT=48263 LHOST=serveo.net apk=outlan.apk
-|    ╰──────────────────────➤ Payload=android/meterpreter/reverse_tcp
-╰──bfftp───➤─user─passwd─ip─➤ Start a brute force attack at ftp server
-|    ╰──────────────────────➤ example: i-Haklab bfftp users.txt passwords.txt 0.0.0.0
-
-╰──bfmail──➤──email─passwd──➤ Start a brute force attack
-|    ╰──────────────────────➤ at email(hotmail/gmail) account
-|    ╰─────➤─────gmail──────➤ ex: i-Haklab bfgmail victim@gmail.com passwords.txt
-|    ╰─────➤──hotmail/live──➤ ex: i-Haklab bfgmail victim@live.com passwords.txt
-|──ESmsg───➤─encode/decode──➤ Encode|decode secret message into a ASCII file.
-╰forwarding➤────────────────➤ Start a SSH client to request TCP port forwarding
-|    ╰──────────────────────➤ from server and proxy.
-|    ╰─────➤──port_number───➤ Set a specific port number 
-|                  ╰────────➤ (default 4546 or 80 for rooted device)
-|    ╰─────➤───subdomain────➤ Set a specitic subdomain
-|    ╰──────────────────────➤ ex: i-Haklab forwarding <myport> <my-subdomain>
-╰─handler──➤──file.rc name──➤ Start handler on msfconsole with previous setting
-╰─payexe───➤──inlan/outlan──➤ Create a coded payload .exe with msfvenom
-|               ╰─────|─────➤ LPORT=4546 Payload=windows/meterpreter/reverse_tcp
-|                     ╰─────➤ LPORT=48263 Payload=windows/meterpreter/reverse_tcp
-|                     ╰─────➤ LHOST=serveo.net file=outlan.exe
-╰─paylink──➤─pc/nexam/soa5──➤ Create an infected link with payload
-|             ╰───|────|────➤ Targets: [0]generic [1]windows [2]macOS [3]linux
-|                 |    |      ex: i-Haklab paylink pc 2
-|                 ╰────|────➤ For targets [0]nexxus and [29]samsung
-|                      |      ex: i-Haklab paylink nexam 29
-|                      ╰────➤ For android5 operative system only
-╰─paypdf───➤────────────────➤ Create a pdf file with a reverse payload
-╰─share────➤upload/download─➤ Share files and directories remotely and securely
-|             ╰───────|─────➤ Upload file and/or directory to share
-|             ╰───────|─────➤ ex: i-Haklab share upload file.txt password(optional)
-|                     ╰─────➤ Download files and/or directory shared
-|                     ╰─────➤ ex: i-Haklab share download https://send.vis.ee/download/...
-╰─shodan───➤────────────────➤ Search vulnerable webcam servers using metasploit
-|__________________________________________________________________________________________\n\n"
+running(){
+        for i in . .. ... ....;do
+                printf "$G$(clear)(_>)─➤ i-Haklab running $i\n$W"
+                sleep 0.1
+        done
 }
-#╰─phishing─➤──site─redirect─➤ Clone a specific website for phishing tests
-#|    ╰──────────────────────➤ Available: facebook mfacebook github google
-#|    ╰──────────────────────➤ instagram netflix spotify twitter
-#|    ╰──────────────────────➤ ex: i-Haklab mfacebook facebook.comexport -f Menu
+export -f running
+
+STDERROOT(){ printf "$R\n(_>)─➤$W Rooted device required";exit;}
+export -f STDERROOT
+
+chk-iHaklab() {
+	until [ -d $iHAKLAB ]; do
+		printf "$R\n(_>)─➤ i-Haklab needed$W |$Y Do you wanna install it?$W\n"
+        	while read -p "(yes/no)─➤ " yesorno && [ -z $yesorno ]; do
+                	continue
+        	done
+        	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
+                	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
+                	cd ~/i-Haklab;bash setup-lite
+        	else
+                	printf "$Goke\n(_>)─➤ Have a nice hacking day!!\n$W"
+                	exit
+        	fi
+	done
+}
+export -f chk-iHaklab
+
+chk-Cuser() {
+	while [ ! $(id -u) -ne 0 ]; do
+        	printf "$R\n(_>)─➤$W You need to be a common user\n"
+        	exit
+	done
+}
+export -f chk-Cuser
+
+chk-Ruser() {
+	while [ ! $(id -u) -eq 0 ]; do
+		printf "$R\n(_>)─➤ You need to be a root user$W\n"
+		exit
+	done
+}
+export -f chk-Ruser
 
 chk-api() {
-        command -v termux-open > /dev/null || { printf "$R[w]->$W termux-tools needed$R |$W please install it"; exit; }
+        command -v termux-open > /dev/null || { printf "$R(_>)─➤$W termux-tools needed$R |$W run i-Haklab install termux-tools"; exit; }
 }
 export -f chk-api
 
 chk-sudo() {
-        command -v sudo > /dev/null || { printf "$R[w]->$W sudo command needed$R |$W please install it"; exit; }
+        command -v sudo > /dev/null || { printf "$R(_>)─➤$W sudo command needed$R |$W please install it"; exit; }
 }
 export -f chk-sudo
 
+chk-root(){
+        if [[ -x /system/xbin/su ]] || [[ -x /su/bin/su ]] || [[ -x /sbin/su ]];then
+		chk-sudo
+                return 0
+        else
+                return 1
+        fi
+        }
+export -f chk-root
+
 chk-msf() {
-        command -v msfconsole > /dev/null || { printf "$R\n[W]->$W Metasploit needed$R |$W please install it"; exit; }
+        command -v msfconsole > /dev/null || { printf "$R\n(_>)─➤$W Metasploit needed$R |$W run i-Haklab install metasploit";exit; }
 }
 export -f chk-msf
 
+chk-java() {
+command -v java >/dev/null || { printf "$R\n(_>)$W java needed$R |$W run i-Haklab install java";exit; }
+}
+export -f chk-java
+
 chk-php() {
-        command -v php > /dev/null || { printf "$R\n[W]->$W php not found$R |$W run apt install php"; exit; }
+        command -v php > /dev/null || { printf "$R\n(_>)─➤$W php not found$R |$W run i-Haklab install php"; exit; }
 }
 export -f chk-php
 
 chk-ssh() {
-        command -v ssh > /dev/null || { printf "$R\n[W]->$W ssh not found$R |$W run apt install openssh"; exit; }
+        command -v ssh > /dev/null || { printf "$R\n(_>)─➤$W ssh not found$R |$W run i-Haklab install openssh"; exit; }
 }
 export -f chk-ssh
 
 chk-mega() {
-        command -v megadl > /dev/null || { printf "$R\n[W]->$W megatools not found$R |$W run apt install megatools"; exit; }
+        command -v megadl > /dev/null || { printf "$R\n(_>)─➤$W megatools not found$R |$W run i-Haklab install megatools"; exit; }
 }
 export -f chk-mega
 
 chk-hydra() {
-        command -v hydra > /dev/null || { printf "$R\n[W]->$W hydra not found$R |$W run apt install hydra"; exit; }
+        command -v hydra > /dev/null || { printf "$R\n(_>)─➤$W hydra not found$R |$W run i-Haklab install hydra"; exit; }
 }
 export -f chk-hydra
 
@@ -175,7 +125,7 @@ chk-tunnel() {
 	elif ping -q -c 1 -W 1 serverless.social >/dev/null 2>&1;then
 		TUNNEL="serverless.social"
 	else
-		printf "$R\n[W]->$W Server not available$R |$W try it later\n"
+		printf "$R\n(_>)─➤$W Server not available$R |$W try it later\n"
 		exit
 	fi
 }
@@ -186,16 +136,64 @@ chk-snow() {
 }
 export -f chk-snow
 
+Menu() {
+	printf "$Y\n(_>)─➤$W i-Haklab v.3.0 (c) 2021 by @Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. If the law is violated with it's use, this would be the responsibility of the user who handled it.\n$Y\nSyntax:$W i-Haklab [-arg-] [-option-]\n
+$Y OPTIONS$W|$Y   Arguments$W   |$Y    Description$W
+╰─about─────+──<name─of─tool>───➤ Show informations about tool/framework
+|   ╰───example─────────────────{─i-Haklab about crunch─}
+╰─help/-h───➤───────────────────➤ Show this help menu
+╰─install───+──<name─of─tool>───➤ Install an specifics tools/frameworks
+|   ╰───────+─────alltools──────➤ Install all tools/frameworks available on i-Haklab
+╰reinstall──➤───────────────────➤ Re-configure i-Haklab at default settings
+╰─remove────+──<name─of─tool>───➤ Remove an specifics installed tools/frameworks
+|   ╰───────+─────alltools──────➤ Remove all installed tools/frameworks
+╰─restore───➤───────────────────➤ Restore the main directory to fix some bugs
+╰─root──────➤───────────────────➤ Simulates a super user environment
+╰─show──────+─────alltools──────➤ List all tools/frameworks available on i-Haklab
+|   ╰───────+──────tools────────➤ Show all installed tools/framewotks
+|   ╰───────+──────games────────➤ Show all games available to play on Termux
+|   ╰───────+──────books────────➤ Show all books available to download
+|   ╰───────+─────tutorials─────➤ Show tutorials available
+|   ╰───────+───────QG──────────➤ Show quick guides available
+╰speedtest──➤───────────────────➤ Run a speed test of your network
+╰─update────➤───────────────────➤ Update i-Haklab
+╰─version───➤───────────────────➤ Show i-Haklab version installed
+╰─weechat───➤───────────────────➤ Connect with irc Ivam3byCinderella chat
+|           |                   |
+|           |                   |
+  $Y [--] Automatitation Arguments [--]$W
+  OPTIONS  |     ARGUMENTS      |    DESCRIPTIONS
+╰───bf─────+─ftp/mail+IP/email──➤ Brute force attack at server ftp or smtp(hotmail|live|gmail)
+|    ╰──example─for─ftp+IP──────{─i-Haklab bf ftp 10.10.10.16
+|    ╰──example─for─mail+email──{─i-Haklab bf mail ivam3@hotmail.com
+|──ESmsg───➤───<encode/decode>──➤ Encode|decode secret message into a ASCII file.
+╰forwarding➤─<port─+─subdomain>─➤ Start a SSH client to request TCP port forwarding
+|    ╰──example─────────────{─i-Haklab forwarding 4444 my-subdomain-}
+╰─handler──+─<nome─of─file.rc>──➤ Start handler on msfconsole with previous setting
+|─payapk───+─<tunnelDNS─+─port>─➤ Create a coded payload apk
+|    ╰──example─for─outlan──────{─i-Haklab payapk 6.tcp.ngrok.io 23453─}
+|─payexe───+─<tunnelDNS─+─port>─➤ Create a coded payload .exe
+|    ╰──example─for─inlan───────{─i-Haklab payapk 192.168.0.1 8080─}
+|─paypdf───+─<tunnelDNS─+─port>─➤ Create a coded payload .pdf
+|    ╰──example─for─default─set─{─i-Haklab payapk─}
+╰─share────+─<upload/download>──➤ Share files and directories remotely and securely
+|               ╰───────|───────{─i-Haklab share upload file.txt password(optional)─}
+|                       ╰───────{i-Haklab share download https://send.vis.ee/download/..─}
+╰─shodan───➤────────────────────➤ Search vulnerable webcam servers using metasploit
+|__________________________________________________________________________________________\n\n"
+}
+export -f Menu
+
 phishing-CredsResults() {
 	ACCOUNT=$(grep -o 'Account:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
 	if [ ! -z $ACCOUNT ]; then
-		printf "$G\n[+]-> ACCOUNT:$W$ACCOUNT"
+		printf "$G\n(_>)─➤ ACCOUNT:$W$ACCOUNT"
 		echo $ACCOUNT >> $TMP_PATH/creds.txt
 		sleep 0.5
 	fi
 	PASSWD=$(grep -o 'Pass:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
 	if [ ! -z $PASSWD ]; then
-		printf "$G\n[+]-> PASSWORD:$W$PASSWD"
+		printf "$G\n(_>)─➤ PASSWORD:$W$PASSWD"
 		echo $PASSWD >> $TMP_PATH/creds.txt
 		sleep 0.5
 	fi
@@ -207,62 +205,62 @@ IP=$(grep -a 'IP:' $TMP_PATH/ip.txt | cut -d " " -f2 | tr -d '\r' | head -n1)
 IPTRACKER=$(curl -s -L "www.ip-tracker.org/locator/ip-lookup.php?ip=$IP" --user-agent "Mozilla/5.0 (X11: Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.63 Safari/537.31" > $TMP_PATH/iptracker.log)
 
 if [ ! -z $IP ]; then 
-	printf "$G\n[+]-> IP:$W$IP"
+	printf "$G\n(_>)─➤ IP:$W$IP"
 	echo $IP >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 
 UA=$(grep 'User-Agent:' $TMP_PATH/ip.txt | cut -d '"' -f2 | head -n1 | awk '{print $1 $2 $3 $4 $5 $6}')
 if [ ! -z $UA ]; then
-	printf "$G\n[+]-> User Agent$W$UA"
+	printf "$G\n(_>)─➤ User Agent$W$UA"
 	echo $UA >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 IP_SPEED=$(grep -o "IP Address Speed:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$IP_SPEED' ]; then
-	printf "$G\n[+]-> IP Address speed:$W$IP_SPEED"
+	printf "$G\n(_>)─➤ IP Address speed:$W$IP_SPEED"
 	echo $IP_SPEED >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 IP_CURRENCY=$(grep -o "IP Currency:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$IP_CURRENCY' ]; then
-	printf "$G\n[+]-> IP Currency:$W$IP_CURRENCY"
+	printf "$G\n(_>)─➤ IP Currency:$W$IP_CURRENCY"
 	echo $IP_CURRENCY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 CONTINENT=$(grep -o "Continent.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "<" -f1)
 if [ ! -z '$CONTINENT' ]; then
-	printf "$G\n[+]-> Continent:$W$CONTINENT"
+	printf "$G\n(_>)─➤ Continent:$W$CONTINENT"
 	echo $CONTINENT >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 COUNTRY=$(grep -o "Country:.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "&" -f1)
 if [ ! -z $COUNTRY ]; then
-	printf "$G\n[+]-> Country:$W$COUNTRY"
+	printf "$G\n(_>)─➤ Country:$W$COUNTRY"
 	echo $COUNTRY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 STATE=$(grep -o "tracking lessimpt.*" $TMP_PATH/iptracker.log | cut -d "<" -f1 | cut -d ">" -f2)
 if [ ! -z '$STATE' ]; then
-	printf "$G\n[+]-> State:$W$STATE"
+	printf "$G\n(_>)─➤ State:$W$STATE"
 	echo $STATE >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 CITY=$(grep -o "City Location:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z $CITY ]; then
-	printf "$G\n[+]-> City:$W$CITY"
+	printf "$G\n(_>)─➤ City:$W$CITY"
 	echo $CITY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 ISP=$(grep -o "ISP:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z $ISP ]; then
-	printf "$G\n[+]-> ISP:$W$IPS"
+	printf "$G\n(_>)─➤ ISP:$W$IPS"
 	echo $ISP >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 AS_NUM=$(grep -o "AS Number" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$AS_NUM' ]; then
-	printf  "$G\n[+]-> AS Number:$W$AS_NUM"
+	printf  "$G\n(_>)─➤ AS Number:$W$AS_NUM"
 	echo $AS_NUM >> $TMP_PATH/creds.txt
 	sleep 0.5 
 fi
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,204 +1,198 @@
 #!/data/data/com.termux/files/usr/bin/bash
-#This script will install i-Haklab v.1.5 2020 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3.
+#This script will install i-Haklab v.3.0 2021 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3.
 IFS=$'\n\t'
 trap ctrl_c 2
-PARTITION=$(echo "$PWD" | grep -o sdext2)
-iHDB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
+ctrl_c() { printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";}
 
-command -v curl >/dev/null 2>&1 || apt install curl -y >/dev/null 2>&1
-curl -Ls ${iHDB}/libexec/colors -o /data/data/com.termux/files/usr/libexec/colors
-source /data/data/com.termux/files/usr/libexec/colors
+printf "Running..."
+[[ -d $PREFIX/share/i-Haklab ]]	|| cp -r $PWD/../i-Haklab $PREFIX/share/
+source $PREFIX/share/i-Haklab/.set/var/variables
+source $iHAKLAB/.set/functions/functions
+chk-Cuser
+clear;banner;sleep 3
+${which} mkdir -p ~/.termux && echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" > ~/.termux/termux.properties && echo "$rst"
 
-ctrl_c(){ printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";}
-
-while [ ! $(id -u) -ne 0 ]; do
-	printf "$R\n[W]─➤ You need to be a common user to install i-Haklab$W\n"
-	exit
-done
-until [ -d /data/data/com.termux/files/home/i-Haklab ]; do
-        printf "$R\n[W]─➤ i-Haklab directory must to be in home directory$W\n"
-	exit
-done
-
-clear;curl -Ls "${iHDB}/libexec/banner/IbyC"|bash
-
-mkdir -p $HOME/.termux && echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" > $HOME/.termux/termux.properties && echo "$rst"
-
-if [ -d $HOME/.local ]; then
-	rm -rf $HOME/.local
+if [ -d ~/.local ]; then
+	rm -rf ~/.local
 fi
-if [ -d $HOME/.config ]; then
-	rm -rf $HOME/.config
+if [ -d ~/.config ]; then
+	rm -rf ~/.config
 fi
 if command -v fish ;then yes|apt remove fish && apt autoremove; fi
 
-printf "$Y\n[!]─➤$W Head to app configuration and provides storage permissions to termux$Y\n ╰─➤$W when finished$G press enter\n$W"
+printf "$Y\n(_>)─➤$W Head to app configuration and provides storage permissions to termux.$Y\n ╰─➤$W when finished$G press enter\n$W"
 read enter
 
 #::::::::::Installation of dependencies::::::::::::#
+printf "$G(_>)─➤$W Upgrading and installing Termux packages.\n"
 yes|pkg update && pkg upgrade
-for repo in fish root-repo unstable-repo fortune util-linux coreutils vim python python2 ruby perl clang curl wget make openssl openssl-tool php zip unzip tar w3m neofetch weechat irssi tor torsocks proxychains-ng htop bison megatools findutils git apr apr-util openssh apache2 mariadb php-apache pkg-config termux-api termux-tools termux-tools ncurses-utils ncurses postgresql termux-elf-cleaner cmatrix figlet man termux-api axel fortune apksigner autoconf libffi libgmp libpcap readline libsqlite libgrpc libiconv libcaca libtool libmpc libmpc-static libmpfr libmpfr-static libxml2 libxml2-static libxml2-utils libxslt libxslt-static libsodium libsodium-static zlib libassuan libgcrypt libgpg-error gnupg gpgme dnsutils debianutils sqlite dirb mlocate sqlmap crunch translate-shell ffsend; do
+for repo in fish root-repo unstable-repo fortune util-linux coreutils vim python python2 ruby perl clang curl wget gawk make openssl openssl-tool php zip unzip tar w3m neofetch weechat irssi tor torsocks proxychains-ng htop bison megatools findutils git apr apr-util openssh apache2 mariadb php-apache pkg-config termux-api termux-tools termux-tools ncurses-utils ncurses postgresql termux-elf-cleaner cmatrix figlet man termux-api axel fortune apksigner autoconf libffi libgmp libpcap readline libsqlite libgrpc libiconv libcaca libtool libmpc libmpc-static libmpfr libmpfr-static libxml2 libxml2-static libxml2-utils libxslt libxslt-static libsodium libsodium-static zlib libassuan libgcrypt libgpg-error youtubedr gnupg gpgme dnsutils debianutils sqlite dirb mlocate sqlmap crunch translate-shell ffsend x11-repo; do
 	GOTIT=$(pkg list-installed | grep -oE $repo)
 	PKG=$(pkg list-all|grep -o $repo)
 	if [ ! -z "$PKG" ] && [ -z "$GOTIT" ];then
-		printf "$G\n[+]─➤$W Installing the repository $repo\n"
+		printf "$G(_>)─➤$W Installing the repository $repo.\n"
 		yes|pkg install $repo >/dev/null 2>&1
 	elif [ ! -z "$PKG" ] && [ ! -z "$GOTIT" ]; then
 		continue
 	else
-		printf "$R\n[w]─➤$W The repository $repo is not candidate\n"
+		printf "$R(_>)─➤$W The repository $repo is not candidate.\n"
 		sleep 1
 	fi
 done
-updatedb
-printf "$G\n[+]─➤$W Installing required python modules\n"
-for v in python python2 ; do
-	$v -m pip --no-color --quiet install --upgrade pip
-done
-
-for module in trufflehog wheel speedtest-cli scapy wfuzz h8mail objection frida; do
-        for v in python python2 ; do
-		$v -m pip --no-color --quiet install $module 
-	done
-done
-
-#::::::::::Searching for root permissions::::::::::::#
-printf "$G\n[+]─➤$W Checking for root permissions ..";
-CHECKROOT=$(bash /data/data/com.termux/files/home/i-Haklab/.set/to-install/check-root)
-USR=$(whoami)
-if [ $CHECKROOT = "root" ]; then
-	printf "$G. GOT IT!!$W\n"
-	printf "$G\n[+]─➤$W Build root enviroment ..";
-	command -v sudo > /dev/null || bash /data/data/com.termux/files/home/i-Haklab/.set/to-install/instasudo
-	if [ -e /data/data/com.termux/files/home/.suroot/.bashrc ]; then
-		if [ ! -O /data/data/com.termux/files/home/.suroot/.bashrc ]; then
-			sudo chown $USR:$USR -R /data/data/com.termux/files/home/.suroot
-		fi
-	else
-		if [ ! -d /data/data/com.termux/files/home/.suroot ]; then
-			mkdir /data/data/com.termux/files/home/.suroot
-		fi
-	fi
-        echo "PS1=\"\[\e[33m\][!] \[\e[31m\]Press\[\e[32m\] Ctrl d\[\e[31m\] to log out\[\e[32m\] ➤ \[\e[m\]\"" > /data/data/com.termux/files/home/.suroot/.bashrc
-        echo "export TERM=xterm-256color" >> /data/data/com.termux/files/home/.suroot/.bashrc
-        echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> /data/data/com.termux/files/home/.suroot/.bashrc
-        echo "export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/xbin:/system/bin" >> /data/data/com.termux/files/home/.suroot/.bashrc
-        echo "HOME=/data/data/com.termux/files/home" >> /data/data/com.termux/files/home/.suroot/.bashrc
-	echo "fish" >> /data/data/com.termux/files/home/.suroot/.bashrc
-        echo "#          i-Haklab by @Ivam3" >> /data/data/com.termux/files/home/.suroot/.bashrc
-	printf "$G. DONE!!$W\n"
+printf "$G(_>)─➤$W Installing Abhacker repositories."
+if [ ! -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ];then
+	TMPabh=$(mktemp)
+	wget -q --tries=20 "${iHDB}/fix-tools/instAbhackerRepo" -O $TMPabh
+        chmod +x $TMPabh
 fi
 
-#::::::::::Definition of variable i-Haklab::::::::::::#
-printf "$G\n[+]─➤ Getting access to external storage..$W";
-sleep 1
+#::: UPDATING LOCATE DATA BASE :::#
+printf "$G(_>)─➤$W Updating data base."
+${which} updatedb
+printf "$G. DONE$W"
+
+printf "$G(_>)─➤$W Installing required python modules.\n"
+for v in python python2 ; do
+	$v -m pip --no-color --quiet --no-cache-dir install --upgrade pip
+done
+for module in trufflehog wheel speedtest-cli scapy wfuzz h8mail objection frida; do
+        for v in python python2 ; do
+		$v -m pip --no-color --quiet --no-cache-dir install $module 
+	done
+done
+
+#::::::::::Definition of variable TOOLS::::::::::::#
+printf "$G\n(_>)─➤ Getting access to external storage..$W";
 yes|termux-setup-storage
-SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
-if [ ! -z $SDCARD ] && [ -z $PARTITION ]; then
-	mkdir -p $SDCARD/roothome
-	until [ -d $SDCARD/roothome ]; do
-		printf "$R. Access denied$W";
-		sleep 1
-		printf "$Y. Retrieving$W";
-		sleep 0.5
-		mkdir -p $SDCARD/roothome
-	done
-#	until [ -O $SDCARD/roothome ] && [ $CHECKROOT = "root" ]; do
-#		printf "$G DONE!!$W\n"
-#		sleep 1
-#		printf "$Y\n[!]─➤ Fixing permissions...$W"
-#		sleep 0.5
-#		sudo chown $USR:$USR $SDCARD/roothome
-#	done
+if [ -w $TOOLS ];then
 	printf "$G. DONE!!$W\n"
-	sleep 1
-	printf "$G\n[+]─➤ Moving i-Haklab directory to external storage..$W";
-        cp -r $HOME/i-Haklab $SDCARD/roothome/
-	until [ -d $SDCARD/roothome/i-Haklab ]; do
-		printf "$R. Access denied$W";
-		sleep 1
-		printf "$Y. Retrieving$W";
-		sleep 0.5
-		cp -r $HOME/i-Haklab $SDCARD/roothome/
-	done
-	rm -rf $HOME/i-Haklab
-	iHAKLAB=$SDCARD/roothome/i-Haklab
-	printf "$G. DONE!!$W\n"
-elif [ ! -z $PARTITION ] || [ -d /data/data/com.termux ]; then
-        iHAKLAB=/data/data/com.termux/files/home/i-Haklab
 else
-        printf "$R\n[W]─➤ STORAGE ACCESS DENIED$W\n"
-	ctrl_c;exit
+	printf "$R. FAIL!!$W"
 fi
 
 #::::::::::Installation of Ohmyfish::::::::::::#
-printf "$G\n[+]─➤ Installing interactive shell..$W";
+printf "$G\n(_>)─➤ Installing interactive shell.$W"
+[[ -d ~/.local/share/omf ]] &&  rm -rf ~/.local/share/omf
+[[ -d ~/.config/omf ]] && rm -rf ~/.config/omf/
+git config --global core.autocrlf
 curl -Ls http://get.oh-my.fish | fish
-echo "if status --is-login" >> $PREFIX/etc/fish/config.fish
-echo "bash /data/data/com.termux/files/usr/var/log/login-termux" >> $PREFIX/etc/fish/config.fish
-echo "end" >> $PREFIX/etc/fish/config.fish
-echo "" >> $PREFIX/etc/fish/config.fish
-echo "function on_exit --on-event fish_exit" >> $PREFIX/etc/fish/config.fish
-echo "echo 'Have a nice hacking day!!'" >> $PREFIX/etc/fish/config.fish
-echo "sleep 1" >> $PREFIX/etc/fish/config.fish
-echo "end" >> $PREFIX/etc/fish/config.fish
-echo "" >> $PREFIX/etc/fish/config.fish
-echo "set fish_theme bobthefish" >> $PREFIX/etc/fish/config.fish
-echo "set HOME /data/data/com.termux/files/home" >> $PREFIX/etc/fish/config.fish
-echo "set GOPATH /data/data/com.termux/files/home/go" >> $PREFIX/etc/fish/config.fish
-echo "alias LOCALHOST=\"ifconfig wlan0 | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v 255\"" >> $PREFIX/etc/fish/config.fish
-echo "alias serverapache=\"apachectl\"" >> $PREFIX/etc/fish/config.fish
-echo "alias postgresql=\"pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql\"" >> $PREFIX/etc/fish/config.fish
-echo "alias traductor=\"gawk -f (curl -Ls git.io/translate | psub) -- -shell\"" >> $PREFIX/etc/fish/config.fish
-echo "" >> $PREFIX/etc/fish/config.fish
-sed -i "22a set iHAKLAB $iHAKLAB" $PREFIX/etc/fish/config.fish
-THEME=$(mktemp)
-echo "#!/bin/env fish" >> $THEME
-echo "#" >> $THEME
-echo "omf install bobthefish" >> $THEME
-fish $THEME >/dev/null 2>&1
-rm $THEME
+cat <<- CONF >> $PREFIX/etc/fish/config.fish
+if status --is-login
+bash /data/data/com.termux/files/usr/var/log/login-termux
+end
+
+function on_exit --on-event fish_exit
+rm -rf $TMPDIR/*
+echo 'Have a nice hacking day!!'
+sleep 1
+end
+
+set fish_theme bobthefish
+set HOME /data/data/com.termux/files/home
+set GOPATH /data/data/com.termux/files/home/go
+set GOROOT /data/data/com.termux/files/usr/lib/go
+set iHAKLAB /data/data/com.termux/files/usr/share/i-Haklab
+alias LOCALHOST="ifconfig wlan0 | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v 255"
+alias serverapache="apachectl"
+alias postgresql="pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql"
+alias traductor="gawk -f (curl -Ls git.io/translate | psub) -- -shell"
+CONF
+TMP_fish=$(mktemp)
+cat <<- CONF > $TMP_fish
+#!/bin/env fish
+omf install bobthefish
+CONF
+fish $TMP_fish >/dev/null 2>&1
+rm $TMP_fish
+cat <<- CONF > $PREFIX/etc/bash.bashrc
+# Command history tweaks:
+# - Append history instead of overwriting
+#   when shell exits.
+# - When using history substitution, do not
+#   exec command immediately.
+# - Do not save to history commands starting
+#   with space.
+# - Do not save duplicated commands.
+shopt -s histappend
+shopt -s histverify
+export HISTCONTROL=ignoreboth
+chsh -s fish
+# Default command line prompt.
+PROMPT_DIRTRIM=2
+PS1='\[\e[0;32m\]\w\[\e[0m\] \[\e[0;97m\]\$\[\e[0m\] '
+
+# Handles nonexistent commands.
+# If user has entered command which invokes non-available
+# utility, command-not-found will give a package suggestions.
+if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then
+        command_not_found_handle() {
+                /data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
+        }
+fi
+CONF
+
+printf "$G\n(_>)─➤ Installing VIM predictable text..$W";
 if [ -d ~/.vim ];then
 	rm -rf ~/.vim
 fi
-wget -q ${iHDB}/to-install/iHaklabvim.zip -O ~/iHaklabvim.zip
-if [ -e ~/iHaklabvim.zip ]; then
-	cd;unzip -q ~/iHaklabvim.zip
-	mv ~/vim ~/.vim
+wget -q --tries=20 ${iHDB}/to-install/iHaklabvim.zip -O $TMPDIR/iHaklabvim.zip
+if [ -e $TMPDIR/iHaklabvim.zip ]; then
+	unzip -q $TMPDIR/iHaklabvim.zip -d $TMPDIR
+	rm -f $TMPDIR/iHaklabvim.zip
+	mv $TMPDIR/vim ~/.vim
+	printf "$G. DONE!!$W"
 else
-	printf "$R\n[W]─➤$W VIM text predictable failure\n"
-	sleep 2
+	printf "$R. FAIL!!$W"
 fi
-bash $iHAKLAB/.set/to-install/functions
+sleep 2
+wget -q --tries=20 $iHDB/functions/unset.fish -O ~/.config/fish/functions/unset.fish
 bash $iHAKLAB/.set/to-install/i-Haklab_login
-gem install fortune
-if [ -e ~/ivam3-Haklab ]; then
-	rm -rf ~/ivam3-Haklab
-fi
-printf "$G. DONE!!$W\n"
-sleep 1
 
 #::::::::::Insatalling i-Haklab tools::::::::::::#
-printf "$G\n[+]─➤ Installing binary tools..$W";
-TARGET=$(ls $iHAKLAB/.set/bin)
-for exe in ${TARGET[*]}; do
-	wget ${iHDB}/bin/$exe -O $PREFIX/bin/$exe -q
-	chmod +x $PREFIX/bin/$exe
-done
-printf "$G. DONE!!$W\n"
+printf "$G\n(_>)─➤$W Installing principal external tools."
 sleep 1
-printf "$G\n[+]─➤ Installing principal external tools..$W"
-sleep 1
-for TOOL in DoS-A-Tool ExiF binchecker blackbox crunch vpn tmux-viewer evilurl; do
-	bash $iHAKLAB/.set/to-install/$TOOL
+for TOOL in 
+	IbyC-fixer converter serverphp DoS-A-Tool ExiF embed binchecker blackbox crunch vpn evilurl localtunnel-server pagekite lock;do
+	bash $iHAKLAB/.set/share/install $TOOL
 done
-
-#::::::::::Installation double check::::::::::::#
-if [ -d /data/data/com.termux/files/home/i-Haklab ] && [ -d /data/data/com.termux/files/home/storage/external-1/roothome/i-haklab ]; then
-	rm -rf /data/data/com.termux/files/home/i-Haklab
+if ! command -v msfconsole;then
+printf "$G\n(_>)─➤$W Installing metasploit-framework."
+        bash <(curl -fsSL "http://git.io/abhacker-repo") --install metasploit -y
 fi
-bash $iHAKLAB/.set/libexec/review
+printf "$G\n(_>)─➤$W Downgrading ruby version..";
+        exec $TMPabh --install "ruby=2.7.2" >/dev/null 2>&1
+printf "$G. DONE!!$W\n"
+printf "$G\n(_>)─➤$W Installing ngrok..";
+[[ $(command -v ngrok) ]] && mv $(command -v ngrok) $(command -v ngrok).io
+	exec $TMPabh --install ngrok-server >/dev/null 2>&1
+printf "$G. DONE!!$W\n"
+        rm $TMPabh
+printf "$G\n(_>)─➤$W Downloading brute force wordlist$G\n  ╰───────────➤$W it could take a while..";
+git clone --quiet https://github.com/jeanphorn/wordlist $iHAKLAB/wordlist
+wget -q --tries=20 https://www.scrapmaker.com/data/wordlists/dictionaries/rockyou.txt -O $iHAKLAB/wordlist/rockyou.txt
+printf "$G. DONE!!$W\n"
 
-printf "$Y\n\n[!]─➤$G i-Haklab installed !!!$Y |$W Please restart Termux and enjoy it!!\n\n"
+#::::::::::Searching for root permissions::::::::::::#
+if chk-root;then
+	wget -q --tries=20 $iHDB/bin/sudo -O $PREFIX/bin/sudo
+        if [[ -e ~/.suroot/.bashrc ]];then
+                [[ -O ~/.suroot/.bashrc ]] || sudo chown $USER:$USER -R ~/.suroot/
+        else
+		[[ -d ~/.suroot ]] || mkdir ~/.suroot
+        fi
+        cat <<- CONF > ~/.suroot/.bashrc
+PS1=\"\[\e[33m\][!] \[\e[31m\]Press\[\e[32m\] Ctrl d\[\e[31m\] to log out\[\e[32m\] ➤ \[\e[m\]\""
+export TERM=xterm-256color
+export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
+export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/xbin:/system/bin
+HOME=/data/data/com.termux/files/home
+fish
+#          i-Haklab by @Ivam3
+CONF
+fi
 
-#		@Ivam3
+[[ $PWD != $iHAKLAB ]] && rm -rf $PWD
+bash $iHAKLAB/.set/share/review #LOGFILE
+
+printf "$Y\n\n(_>)─➤$G i-Haklab installed !!!$Y |$W Please restart Termux and enjoy it!!\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n\n"
+#		i-Haklab by @Ivam3
