update function ngrokssh

diff --git a/.deb/home/.local/libexec/i-Haklab/ngrokssh b/.deb/home/.local/libexec/i-Haklab/ngrokssh
--- a/.deb/home/.local/libexec/i-Haklab/ngrokssh
+++ b/.deb/home/.local/libexec/i-Haklab/ngrokssh
@@ -5,12 +5,31 @@ source ${HOME}/.local/etc/i-Haklab/variables
 source $iHETC/functions
 
 chk-pkg ssh openssh
-banner
+[[ $# -gt '3' ]] || STDERR
 
-[[ -e ${HOME}/.ssh/id_rsa.pub ]] && {
-	printf $G"(_➤)$W Running Ngrok server by SSH connection.";
-	ssh -R 443:localhost:$argv -oHostKeyAlgorithms=+ssh-rsa \
-		-oPubkeyAcceptedKeyTypes=+ssh-rsa tunnel.us.ngrok.com;} || {
-		chk-ssh;
-			printf $R"ERROR:$W Ngrok is not set$R |$W run i-Haklab tutorials for a guide\n";
-}
+while getopts "f:p:t:" opt; do
+  case $opt in
+    p) p=$OPTARG
+      [ $p -eq $p 2>/dev/null ] || { STDERR;}
+      ;;
+    t) t=$OPTARG
+      [ $t -eq $t 2>/dev/null ] && { STDERR;}
+      ;;
+    f) f=$OPTARG
+      [[ -e $f ]] || { echo -en "\e[31mE:$W Not such file : $f$Y\n!:$W run i-Haklab tutorials for a guide\n";exit 0;}
+      ;;
+    \?) echo -en $R"E:$W Invalid option: -$OPTARG" >&2 && exit 1 ;;
+    :) echo -en $R"E:$W Option -$OPTARG requires an argument." >&2 && exit 1 ;;
+    *) STDERR ;;
+  esac
+done
+
+banner
+printf $G"(_➤)$W Running Ngrok server by SSH connection.\n"
+if [[ -z $f ]]; then
+  ssh -R 443:localhost:$p -oHostKeyAlgorithms=+ssh-rsa \
+  -oPubkeyAcceptedKeyTypes=+ssh-rsa tunnel.us.ngrok.com $t
+else
+  ssh -R 443:localhost:$p -oHostKeyAlgorithms=+ssh-rsa \
+  -oPubkeyAcceptedKeyTypes=+ssh-rsa -i $f tunnel.us.ngrok.com $t
+fi
